In [1]:
from Bprice import *

In [2]:
import pandas as pd
import csv

In [3]:
# from ta.trend import ema_indicator as EMA, sma_indicator as SMA

df = pd.read_csv('btc_price.csv')

In [4]:
# from Bprice.advanced_ta import LorentzianClassification
# from ta.volume import money_flow_index as MFI
lc = LorentzianClassification(
        df,
        
        settings=LorentzianClassification.Settings(
            source=df['close'],
            neighborsCount=21,
            maxBarsBack=4000,
            useDynamicExits=False
        ),
        
        filterSettings=LorentzianClassification.FilterSettings(
            useVolatilityFilter=True,
            useRegimeFilter=True,
            useAdxFilter=True,
            regimeThreshold=-0.1,
            adxThreshold=20,
            
            kernelFilter = LorentzianClassification.KernelFilter(
                useKernelSmoothing = False,
                lookbackWindow = 21,
                relativeWeight = 14.0,
                regressionLevel = 50,
                crossoverLag = 2
            )
        ))

In [5]:
#data   : range rsi 14
#period : price list
#--return list
calculate_rsi(data = df["close"],period=14)

0         0.00
1       100.00
2       100.00
3       100.00
4       100.00
         ...
5025     70.57
5026     67.13
5027     68.27
5028     69.39
5029     70.04
Name: close, Length: 5030, dtype: float64

In [7]:
#open  : price open list
#close : price close list
#--return list
calculate_percent_change(start_prices=df["open"],end_prices=df["close"])

      percent_change
0              -0.37
1               0.07
2               0.04
3               0.01
4               0.02
...              ...
5025           -0.06
5026           -0.41
5027            0.28
5028            0.27
5029            0.16

[5030 rows x 1 columns]

In [9]:
#data   : range ema int
#period : price list
#--return list
calculate_ema(price_series=df["close"],period=14)

0        62840.730000
1        62846.432667
2        62854.989644
3        62863.145692
4        62872.058266
            ...
5025    100850.182283
5026    101040.907312
5027    101244.374337
5028    101457.944425
5029    101664.407835
Name: close, Length: 5030, dtype: float64

In [10]:
#data            : data list or close price
#short_period    : fast default 12 
#long_period     : slow default 26
#signal_period   : signal period default 9
#--return list
calculate_macd(df['close'], short_period=12, long_period=26, signal_period=9)

      MACD_12_26   Signal_9  Histogram_9
0         0.0000     0.0000       0.0000
1         3.4119     0.6824       2.7295
2         8.2087     2.1876       6.0211
3        12.3161     4.2133       8.1028
4        16.4970     6.6701       9.8270
...          ...        ...          ...
5025   1749.1396  1409.6671     339.4725
5026   1707.7547  1469.2846     238.4700
5027   1678.7069  1511.1691     167.5378
5028   1659.0937  1540.7540     118.3397
5029   1637.6053  1560.1243      77.4810

[5030 rows x 3 columns]

In [ ]:
#data   : list price
#period : range sma
#--return list
calculate_sma(data = df["close"],period=14)

In [12]:
#data   : list price
#period : range bollinger
#--return list
calculate_bollinger_bands(price_series=df['close'],period=20)

         BBM_20     BBU_20    BBL_20
0           NaN        NaN       NaN
1           NaN        NaN       NaN
2           NaN        NaN       NaN
3           NaN        NaN       NaN
4           NaN        NaN       NaN
...         ...        ...       ...
5025   99228.08  105075.87  93380.29
5026   99550.96  105319.70  93782.22
5027   99892.16  105518.00  94266.32
5028  100292.08  105532.00  95052.16
5029  100665.07  105531.40  95798.74

[5030 rows x 3 columns]

In [13]:
#data is df  : df
#period      : range atr
calculate_atr(data=df, period=14)

                0
0             NaN
1      305.930000
2      288.730000
3      238.556667
4      232.657500
...           ...
5025  1389.550714
5026  1303.016429
5027  1228.133571
5028  1213.065000
5029  1193.727857

[5030 rows x 1 columns]

In [ ]:
#high is price  : high list
#low is price   : low list
#close is price : close list
#period         : range cci
calculate_cci(close=df["close"],high=df["high"],low=df["low"], period=20)

In [16]:
#high is price  : high list
#low is price   : low list
#close is price : close list
#get di false is get only adx true is get adx,Di,Di- 3parameater
adx = calculate_adx( data=df,period=14,)
# adx = Get_AdxandDi(High=df["high"],Low=df["low"],Close=df["close"],GetDi = False)

In [ ]:
#df is dataframe
#atr_period is range atr 
#mmultiplier is range supertrend
calculate_supertrend(df=df, atr_period=14, multiplier=3)

In [19]:
round_dataframe(df,2)



# ClearFloatDF(df,2)

,Unnamed: 0,open,high,low,close,volume,datetime
0,0,63074.00,63094.01,62742.00,62840.73,768.12,2024-05-10 00:00:00
1,1,62840.72,62968.00,62662.07,62883.50,776.17,2024-05-10 01:00:00
2,2,62883.50,63043.29,62771.76,62910.61,605.45,2024-05-10 02:00:00
3,3,62910.62,62932.15,62793.94,62916.16,586.05,2024-05-10 03:00:00
4,4,62916.16,63008.00,62793.04,62929.99,607.57,2024-05-10 04:00:00
...,...,...,...,...,...,...,...
5025,5025,102764.01,103159.76,102565.63,102698.24,2204.40,2024-12-05 09:00:00
5026,5026,102698.25,102920.00,102260.00,102280.62,1591.37,2024-12-05 10:00:00
5027,5027,102280.62,102672.84,102237.79,102566.91,1395.71,2024-12-05 11:00:00
5028,5028,102566.91,103295.99,102452.95,102846.15,2215.64,2024-12-05 12:00:00
5029,5029,102846.16,103250.00,102684.73,103006.42,1259.18,2024-12-05 13:00:00