In [ ]:
#this fiile for example

In [1]:
from Bprice import *

Initializing Bprice Package Success
version 2

In [2]:

import pandas as pd
import csv

In [24]:
# from ta.trend import ema_indicator as EMA, sma_indicator as SMA

df = pd.read_csv('btc_price.csv')

In [ ]:
#dataframe = df
#decimal = int range float
#--return df 
ClearFloatDF(dataframe=df,decimal=2)

c:\Users\beatk\Desktop\bpric\Bprice\edit_df.py:25: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dataframe = dataframe.applymap(lambda x: round(x, decimal) if isinstance(x, (int, float)) else x)

,Unnamed: 0,open,high,low,close,volume,datetime
0,0,63074.00,63094.01,62742.00,62840.73,768.12,2024-05-10 00:00:00
1,1,62840.72,62968.00,62662.07,62883.50,776.17,2024-05-10 01:00:00
2,2,62883.50,63043.29,62771.76,62910.61,605.45,2024-05-10 02:00:00
3,3,62910.62,62932.15,62793.94,62916.16,586.05,2024-05-10 03:00:00
4,4,62916.16,63008.00,62793.04,62929.99,607.57,2024-05-10 04:00:00
...,...,...,...,...,...,...,...
5025,5025,102764.01,103159.76,102565.63,102698.24,2204.40,2024-12-05 09:00:00
5026,5026,102698.25,102920.00,102260.00,102280.62,1591.37,2024-12-05 10:00:00
5027,5027,102280.62,102672.84,102237.79,102566.91,1395.71,2024-12-05 11:00:00
5028,5028,102566.91,103295.99,102452.95,102846.15,2215.64,2024-12-05 12:00:00
5029,5029,102846.16,103250.00,102684.73,103006.42,1259.18,2024-12-05 13:00:00

In [4]:
# from Bprice.advanced_ta import LorentzianClassification
# from ta.volume import money_flow_index as MFI
lc = LorentzianClassification(
        df,
        
        settings=LorentzianClassification.Settings(
            source=df['close'],
            neighborsCount=21,
            maxBarsBack=4000,
            useDynamicExits=False
        ),
        
        filterSettings=LorentzianClassification.FilterSettings(
            useVolatilityFilter=True,
            useRegimeFilter=True,
            useAdxFilter=True,
            regimeThreshold=-0.1,
            adxThreshold=20,
            
            kernelFilter = LorentzianClassification.KernelFilter(
                useKernelSmoothing = False,
                lookbackWindow = 21,
                relativeWeight = 14.0,
                regressionLevel = 50,
                crossoverLag = 2
            )
        ))

In [5]:
#data   : range rsi 14
#period : price list
#--return list
Get_Rsi(data = df["close"],period=14)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 24.42,
 23.44,
 26.8,
 21.85,
 28.72,
 28.72,
 27.07,
 31.2,
 34.19,
 33.6,
 33.37,
 35.66,
 36.11,
 33.85,
 34.77,
 38.95,
 39.78,
 41.58,
 37.39,
 40.62,
 37.71,
 36.61,
 37.43,
 45.18,
 42.33,
 50.78,
 51.4,
 48.89,
 51.76,
 49.92,
 46.69,
 44.34,
 44.1,
 41.99,
 46.95,
 44.02,
 46.06,
 46.06,
 51.67,
 50.02,
 46.7,
 42.95,
 50.7,
 49.14,
 54.03,
 53.54,
 53.85,
 55.03,
 54.09,
 61.91,
 58.8,
 65.72,
 56.52,
 57.37,
 53.11,
 51.49,
 54.3,
 58.82,
 59.6,
 55.75,
 44.03,
 48.01,
 42.96,
 40.17,
 56.7,
 68.68,
 72.9,
 75.32,
 66.85,
 67.5,
 68.6,
 67.11,
 66.35,
 69.36,
 71.28,
 62.48,
 61.95,
 66.87,
 64.98,
 60.62,
 57.73,
 60.35,
 57.52,
 53.97,
 51.65,
 50.51,
 51.83,
 55.3,
 42.1,
 42.0,
 39.2,
 38.21,
 36.95,
 39.13,
 35.3,
 38.89,
 41.79,
 41.47,
 35.07,
 33.34,
 36.78,
 41.47,
 41.85,
 44.28,
 44.69,
 41.59,
 38.54,
 46.38,
 48.52,
 53.07,
 51.67,
 52.45,
 53.4,
 59.39,
 57.62,
 67.78,
 68.18,
 61.28,
 76.91,
 79.58,
 81.67,
 82.87,
 83.04,
 84.52,
 87.31,
 88.29,
 86.42,
 84.6,
 85.76,
 86.16,
 82.78,
 80.09,
 77.95,
 78.48,
 73.76,
 72.85,
 74.74,
 76.58,
 78.03,
 78.65,
 72.31,
 75.9,
 62.94,
 66.86,
 52.98,
 55.95,
 46.42,
 44.46,
 46.4,
 47.41,
 48.8,
 51.78,
 51.04,
 47.93,
 52.57,
 49.65,
 50.45,
 53.9,
 51.33,
 55.6,
 59.55,
 65.17,
 60.14,
 62.69,
 64.61,
 58.72,
 60.92,
 52.77,
 63.25,
 66.82,
 62.37,
 58.75,
 60.06,
 62.49,
 59.75,
 58.37,
 57.67,
 60.96,
 58.39,
 59.61,
 58.11,
 58.69,
 57.29,
 56.6,
 57.83,
 56.95,
 59.76,
 61.62,
 63.44,
 62.41,
 54.98,
 52.63,
 50.71,
 51.53,
 53.32,
 52.62,
 50.29,
 53.92,
 55.47,
 53.05,
 54.14,
 53.45,
 53.07,
 53.62,
 63.46,
 61.46,
 60.55,
 57.83,
 54.2,
 63.99,
 56.86,
 57.48,
 60.25,
 62.03,
 44.35,
 50.92,
 47.52,
 46.48,
 40.72,
 42.66,
 39.45,
 29.54,
 33.75,
 37.36,
 39.9,
 38.11,
 43.73,
 45.46,
 49.7,
 49.73,
 60.36,
 60.44,
 43.52,
 51.82,
 50.6,
 53.09,
 56.9,
 54.35,
 53.07,
 56.21,
 53.98,
 61.29,
 70.63,
 71.97,
 75.36,
 82.62,
 73.46,
 74.77,
 72.52,
 81.36,
 79.37,
 76.05,
 76.95,
 76.96,
 70.96,
 72.79,
 72.72,
 67.36,
 67.65,
 68.26,
 68.82,
 69.48,
 71.4,
 57.94,
 52.53,
 47.68,
 45.81,
 48.41,
 48.05,
 41.48,
 47.72,
 47.73,
 54.1,
 53.06,
 52.64,
 53.2,
 50.67,
 49.9,
 44.42,
 49.43,
 48.73,
 46.49,
 51.57,
 51.17,
 54.57,
 46.71,
 45.29,
 44.38,
 53.6,
 58.41,
 54.39,
 48.56,
 44.51,
 45.58,
 42.83,
 43.87,
 38.98,
 39.5,
 45.96,
 45.7,
 46.15,
 45.09,
 47.36,
 45.96,
 47.89,
 51.76,
 50.68,
 49.64,
 47.02,
 57.09,
 45.51,
 29.38,
 27.23,
 33.22,
 31.09,
 29.61,
 27.7,
 26.27,
 37.17,
 40.17,
 37.09,
 41.55,
 40.27,
 39.07,
 43.02,
 41.95,
 39.69,
 35.14,
 31.25,
 36.21,
 36.83,
 40.24,
 39.97,
 39.92,
 42.81,
 37.13,
 50.65,
 56.47,
 57.27,
 62.97,
 63.49,
 64.97,
 59.94,
 60.4,
 58.76,
 54.45,
 54.1,
 55.41,
 58.56,
 57.29,
 57.73,
 56.17,
 54.79,
 56.65,
 59.04,
 62.96,
 67.44,
 59.88,
 60.08,
 57.7,
 57.58,
 55.03,
 55.18,
 58.19,
 61.41,
 59.48,
 57.62,
 58.6,
 58.23,
 62.4,
 57.27,
 57.42,
 48.6,
 53.65,
 50.51,
 55.21,
 54.07,
 60.15,
 54.22,
 51.96,
 55.64,
 52.83,
 48.56,
 52.71,
 56.68,
 44.87,
 43.99,
 43.28,
 43.99,
 47.3,
 42.52,
 37.93,
 39.39,
 38.19,
 48.38,
 54.82,
 55.7,
 49.12,
 46.55,
 41.06,
 38.44,
 45.56,
 45.12,
 44.45,
 44.01,
 40.52,
 46.48,
 54.33,
 65.08,
 74.72,
 69.68,
 69.91,
 65.19,
 51.49,
 56.87,
 58.66,
 55.04,
 52.5,
 51.53,
 40.96,
 42.06,
 35.27,
 32.97,
 37.36,
 36.57,
 33.8,
 41.76,
 44.48,
 48.26,
 45.62,
 43.33,
 38.54,
 41.5,
 47.7,
 40.21,
 41.25,
 42.76,
 50.43,
 49.15,
 50.2,
 53.14,
 49.92,
 51.35,
 52.45,
 54.19,
 56.36,
 56.58,
 51.54,
 50.21,
 41.15,
 40.12,
 40.83,
 42.68,
 39.14,
 42.21,
 41.9,
 37.9,
 34.21,
 38.63,
 40.01,
 36.56,
 34.7,
 40.38,
 45.4,
 45.01,
 44.46,
 43.02,
 48.6,
 52.06,
 55.72,
 56.66,
 55.83,
 47.96,
 42.68,
 45.41,
 46.91,
 51.79,
 48.71,
 55.85,
 64.18,
 57.85,
 60.56,
 62.76,
 70.52,
 70.98,
 56.18,
 53.19,
 52.19,
 50.44,
 51.08,
 53.0,
 52.59,
 54.49,
 54.39,
 53.91,
 52.01,
 47.8,
 45.55,
 44.64,
 40.48,
 50.68,
 51.06,
 57.49,
 45.2,
 36.6,
 33.22,
 33.04,
 36.42,
 38.12,
 44.05,
 44.66,
 42.15,
 41.19,
 41.97,
 44.96,
 42.99,
 47.39,
 47.07,
 46.21,
 46.4,
 46.62,
 44.86,
 47.37,
 47.46,
 44.85,
 46.19,
 48.49,
 48.59,
 52.06,
 47.43,
 47.82,
 51.83,
 50.0,
 50.14,
 52.22,
 50.3,
 50.59,
 50.67,
 57.21,
 49.47,
 48.33,
 51.44,
 54.76,
 47.85,
 53.57,
 47.58,
 49.09,
 39.87,
 39.87,
 64.89,
 54.23,
 59.47,
 61.25,
 57.76,
 56.54,
 49.96,
 45.34,
 46.51,
 49.26,
 48.82,
 52.18,
 47.33,
 49.16,
 64.15,
 62.33,
 61.29,
 63.77,
 67.17,
 72.18,
 67.83,
 71.16,
 67.11,
 63.83,
 66.65,
 74.85,
 75.33,
 52.76,
 62.68,
 54.78,
 56.85,
 57.06,
 55.75,
 54.12,
 53.79,
 53.11,
 49.12,
 52.3,
 55.64,
 54.19,
 54.7,
 52.45,
 50.31,
 49.26,
 51.58,
 47.74,
 45.31,
 49.35,
 50.83,
 50.61,
 62.03,
 63.94,
 73.24,
 76.2,
 70.61,
 71.83,
 65.7,
 65.24,
 67.78,
 66.37,
 65.78,
 68.81,
 71.24,
 67.26,
 68.65,
 71.3,
 66.67,
 68.24,
 69.3,
 61.84,
 60.97,
 58.49,
 61.56,
 60.67,
 54.98,
 57.77,
 68.65,
 62.17,
 66.23,
 55.45,
 57.99,
 56.4,
 55.29,
 55.39,
 54.59,
 52.6,
 54.7,
 55.42,
 52.66,
 52.76,
 48.7,
 48.51,
 52.09,
 48.87,
 50.95,
 51.21,
 56.21,
 56.66,
 54.41,
 62.88,
 57.35,
 47.71,
 51.45,
 50.84,
 38.32,
 44.29,
 44.78,
 48.6,
 46.4,
 48.47,
 47.46,
 47.07,
 51.53,
 57.1,
 58.49,
 57.7,
 52.94,
 53.13,
 57.9,
 59.7,
 66.34,
 52.81,
 58.66,
 56.08,
 48.93,
 44.38,
 30.62,
 25.46,
 27.5,
 28.61,
 28.1,
 33.53,
 32.03,
 33.07,
 34.56,
 34.01,
 34.27,
 32.66,
 32.75,
 33.18,
 40.62,
 37.95,
 38.16,
 38.48,
 36.69,
 36.57,
 39.18,
 40.38,
 39.54,
 38.37,
 40.69,
 41.36,
 41.6,
 38.65,
 40.33,
 38.0,
 37.05,
 35.6,
 36.65,
 32.78,
 38.17,
 40.9,
 40.43,
 46.29,
 41.94,
 45.22,
 46.25,
 45.05,
 46.4,
 62.61,
 50.82,
 51.74,
 52.5,
 57.04,
 58.44,
 61.26,
 59.69,
 58.35,
 60.91,
 54.31,
 54.94,
 50.2,
 53.42,
 57.5,
 51.93,
 54.74,
 49.91,
 43.33,
 38.73,
 43.04,
 46.11,
 45.68,
 47.45,
 42.62,
 45.04,
 56.42,
 67.84,
 63.66,
 65.39,
 57.75,
 46.05,
 50.22,
 48.87,
 46.32,
 47.76,
 44.01,
 30.38,
 24.88,
 30.68,
 25.84,
 24.69,
 22.78,
 21.73,
 21.27,
 17.96,
 17.14,
 16.66,
 20.96,
 19.24,
 20.56,
 16.17,
 23.24,
 30.59,
 38.36,
 44.01,
 42.32,
 44.41,
 43.83,
 43.06,
 41.12,
 40.78,
 46.47,
 46.3,
 48.13,
 43.09,
 44.1,
 48.53,
 47.13,
 55.45,
 59.95,
 54.63,
 73.29,
 72.89,
 77.31,
 72.79,
 70.48,
 71.97,
 55.89,
 42.31,
 48.28,
 52.3,
 50.44,
 49.62,
 50.32,
 46.62,
 44.18,
 41.68,
 40.3,
 44.06,
 43.15,
 46.04,
 44.17,
 42.48,
 48.35,
 47.31,
 47.45,
 45.21,
 42.2,
 32.79,
 40.82,
 40.24,
 39.63,
 36.9,
 38.81,
 43.19,
 42.25,
 40.67,
 40.08,
 41.67,
 44.61,
 41.4,
 41.0,
 47.92,
 46.35,
 45.33,
 50.4,
 46.08,
 45.23,
 48.75,
 49.75,
 49.47,
 47.47,
 36.72,
 25.26,
 27.97,
 30.37,
 30.32,
 35.93,
 44.35,
 41.84,
 42.42,
 45.18,
 43.44,
 46.28,
 47.35,
 46.94,
 46.64,
 45.3,
 43.36,
 47.19,
 47.35,
 49.35,
 49.91,
 50.74,
 49.65,
 46.75,
 49.99,
 45.84,
 48.15,
 44.87,
 45.24,
 41.89,
 45.12,
 48.01,
 49.12,
 46.6,
 47.21,
 45.87,
 46.03,
 47.09,
 52.04,
 54.3,
 51.79,
 52.11,
 58.7,
 68.96,
 57.7,
 60.92,
 65.38,
 55.33,
 60.53,
 56.15,
 55.64,
 56.0,
 54.89,
 53.03,
 53.31,
 61.1,
 57.56,
 53.63,
 49.27,
 44.77,
 40.94,
 49.54,
 46.44,
 40.26,
 41.77,
 42.66,
 31.73,
 37.83,
 36.32,
 32.61,
 26.23,
 35.02,
 33.37,
 46.94,
 58.98,
 64.95,
 57.48,
 52.79,
 55.13,
 56.25,
 53.64,
 42.95,
 36.55,
 41.62,
 42.11,
 43.27,
 43.63,
 42.36,
 45.43,
 46.41,
 42.56,
 42.05,
 41.0,
 38.98,
 33.78,
 31.34,
 33.12,
 33.06,
 31.85,
 33.8,
 30.17,
 43.14,
 48.7,
 49.81,
 47.85,
 47.23,
 45.15,
 51.43,
 52.94,
 53.39,
 53.07,
 57.1,
 50.31,
 47.14,
 50.04,
 54.7,
 47.74,
 47.36,
 45.18,
 42.34,
 41.73,
 41.73,
 46.57,
 43.88,
 41.75,
 41.57,
 45.9,
 41.59,
 46.07,
 49.78,
 51.54,
 52.68,
 52.42,
 56.0,
 61.58,
 59.67,
 68.24,
 62.16,
 62.79,
 71.28,
 69.89,
 63.5,
 44.27,
 41.21,
 39.36,
 ...]

In [6]:
#open  : price open list
#close : price close list
#--return list
Get_percen(open=df["open"],close=df["close"])

[np.float64(-0.3698354313980353),
 np.float64(0.06807687754054828),
 np.float64(0.04311146803215562),
 np.float64(0.008806144336204084),
 np.float64(0.021981633971295243),
 np.float64(-0.25744477991419357),
 np.float64(0.6340810604129493),
 np.float64(-0.13928379191337617),
 np.float64(-0.06027457112233578),
 np.float64(0.13797588832487817),
 np.float64(-0.16081874355763326),
 np.float64(0.4350465462835246),
 np.float64(-0.46083997647379477),
 np.float64(-0.006205570062558005),
 np.float64(-3.079375912640463),
 np.float64(-0.22247197892961224),
 np.float64(0.23555664536612891),
 np.float64(-1.1262691056637693),
 np.float64(0.5520694240218108),
 np.float64(-0.00018116813259231516),
 np.float64(-0.32946313517672965),
 np.float64(0.319067844012519),
 np.float64(0.23722619621581895),
 np.float64(-0.08875340980050947),
 np.float64(-0.03289474225242472),
 np.float64(0.15909841380362907),
 np.float64(0.030438575021323615),
 np.float64(-0.26819839061259604),
 np.float64(0.056181357109094776),
 np.float64(0.2567225092979627),
 np.float64(0.050917575082501526),
 np.float64(0.10749265827768413),
 np.float64(-0.3745255744443513),
 np.float64(0.18822171603524698),
 np.float64(-0.2601289036165196),
 np.float64(-0.10203142627191676),
 np.float64(0.042861380264982596),
 np.float64(0.4315433319809994),
 np.float64(-0.2164927808678113),
 np.float64(0.5492602647501179),
 np.float64(0.04415261471425042),
 np.float64(-0.16690849199034363),
 np.float64(0.1890373400302198),
 np.float64(-0.11525037756546917),
 np.float64(-0.2084096218092341),
 np.float64(-0.15900598804553714),
 np.float64(-0.01569282767191312),
 np.float64(-0.13790841206836515),
 np.float64(0.24990961922691607),
 np.float64(-0.18039295818048445),
 np.float64(0.10161332719983988),
 np.float64(0.00022977239730965723),
 np.float64(0.2789922404411192),
 np.float64(-0.0818330471631674),
 np.float64(-0.16956590179101375),
 np.float64(-0.20754271492910906),
 np.float64(0.3781322555298072),
 np.float64(-0.08185098207255656),
 np.float64(0.2622622520881487),
 np.float64(-0.022874431470636218),
 np.float64(0.015961798966705812),
 np.float64(0.05811391406368309),
 np.float64(-0.036720912404365334),
 np.float64(0.408982810362726),
 np.float64(-0.11761830742632491),
 np.float64(0.4393548348185342),
 np.float64(-0.39333747725845364),
 np.float64(0.052383788235890724),
 np.float64(-0.1988075779429795),
 np.float64(-0.07837278325201334),
 np.float64(0.14697236919459142),
 np.float64(0.25762319407754947),
 np.float64(0.04698783423329552),
 np.float64(-0.15773927094966883),
 np.float64(-0.60508780465247),
 np.float64(0.20598169262760818),
 np.float64(-0.3155795324505491),
 np.float64(-0.19349931515116195),
 np.float64(1.06005754945533),
 np.float64(1.3499590027264954),
 np.float64(0.6943521999744598),
 np.float64(0.46745760006142734),
 np.float64(-0.6119668046344675),
 np.float64(0.10101366277200201),
 np.float64(0.16903633667575724),
 np.float64(-0.10242818609817884),
 np.float64(-0.05063741982674145),
 np.float64(0.4049857939423653),
 np.float64(0.28076886448049176),
 np.float64(-0.583074504791074),
 np.float64(-0.0375892505887957),
 np.float64(0.6144434587469693),
 np.float64(-0.1279191802788193),
 np.float64(-0.3013541520715461),
 np.float64(-0.20946949656098973),
 np.float64(0.27095746375657437),
 np.float64(-0.19869688778646116),
 np.float64(-0.25949207689498466),
 np.float64(-0.17560490078451443),
 np.float64(-0.0855904968805739),
 np.float64(0.09883424875569351),
 np.float64(0.26698547183367216),
 np.float64(-1.076610219649406),
 np.float64(-0.010637956648390139),
 np.float64(-0.28111373201651413),
 np.float64(-0.10209985255656752),
 np.float64(-0.12756109275015837),
 np.float64(0.12892302208396073),
 np.float64(-0.37549412551132316),
 np.float64(0.2102603476272),
 np.float64(0.17466291969103134),
 np.float64(-0.026098744186027225),
 np.float64(-0.5827382840569915),
 np.float64(-0.18324028603456638),
 np.float64(0.18755609354254155),
 np.float64(0.2710727657496285),
 np.float64(0.021965530189939065),
 np.float64(0.1371854327638755),
 np.float64(0.023049030084821346),
 np.float64(-0.2127574066445664),
 np.float64(-0.22595919385476645),
 np.float64(0.4193634757443868),
 np.float64(0.1264587860572528),
 np.float64(0.2848770866582822),
 np.float64(-0.08069412117741741),
 np.float64(0.04633279483037204),
 np.float64(0.05503105427583339),
 np.float64(0.3748865245651635),
 np.float64(-0.08285226603278788),
 np.float64(0.8150006332117402),
 np.float64(0.03947327676720076),
 np.float64(-0.3311064911359716),
 np.float64(2.065692736569823),
 np.float64(0.6092139333415597),
 np.float64(0.551866055560752),
 np.float64(0.34902330992609865),
 np.float64(0.052761586228027346),
 np.float64(0.44364311760201647),
 np.float64(1.0311383107730852),
 np.float64(0.4396864873287469),
 np.float64(-0.11417104112748235),
 np.float64(-0.10752169544832317),
 np.float64(0.38917406455724884),
 np.float64(0.13641112155231036),
 np.float64(-0.18519326875861694),
 np.float64(-0.14816014188022944),
 np.float64(-0.11590339100771312),
 np.float64(0.09995522649160138),
 np.float64(-0.2456370473899399),
 np.float64(-0.047634719648009465),
 np.float64(0.2677784603354112),
 np.float64(0.27969254439254343),
 np.float64(0.23358615065444946),
 np.float64(0.10191996273745677),
 np.float64(-0.29337890375137304),
 np.float64(0.5044582136920098),
 np.float64(-0.7410101767101809),
 np.float64(0.48028351634069555),
 np.float64(-1.099625105875252),
 np.float64(0.33564689544153703),
 np.float64(-1.0086769922738008),
 np.float64(-0.24555298766112005),
 np.float64(0.1956765905069625),
 np.float64(0.09929027263978103),
 np.float64(0.13355456408073307),
 np.float64(0.28815498997301603),
 np.float64(-0.06571752554420787),
 np.float64(-0.2809123590737796),
 np.float64(0.4192214603126183),
 np.float64(-0.2562407741261857),
 np.float64(0.06914512717392829),
 np.float64(0.30362768788425476),
 np.float64(-0.20236479547844766),
 np.float64(0.3791950138582911),
 np.float64(0.38899549299778036),
 np.float64(0.6540464518836694),
 np.float64(-0.36290275811819933),
 np.float64(0.3000030236144322),
 np.float64(0.23521190852043333),
 np.float64(-0.4247639152024056),
 np.float64(0.24461630442119417),
 np.float64(-0.6567493176028809),
 np.float64(1.308139843461165),
 np.float64(0.5814239805696162),
 np.float64(-0.39452287362066374),
 np.float64(-0.33987748393843703),
 np.float64(0.17910870220626057),
 np.float64(0.3382270324824397),
 np.float64(-0.2356371906152671),
 np.float64(-0.11862759754822218),
 np.float64(-0.05843380635179306),
 np.float64(0.3780050200983564),
 np.float64(-0.19755609930771587),
 np.float64(0.13216908134490973),
 np.float64(-0.10771873808880641),
 np.float64(0.055598857234236465),
 np.float64(-0.09179168709386039),
 np.float64(-0.04319444527507403),
 np.float64(0.09771938248171294),
 np.float64(-0.04935741959469958),
 np.float64(0.21017533897837826),
 np.float64(0.14538789176217898),
 np.float64(0.14478950698420892),
 np.float64(-0.04669587625875349),
 np.float64(-0.36137382478347513),
 np.float64(-0.1266953645658473),
 np.float64(-0.10397351726314773),
 np.float64(0.04486952803604588),
 np.float64(0.09658260109484264),
 np.float64(-0.032382407830866794),
 np.float64(-0.1049254544725873),
 np.float64(0.17406639734055754),
 np.float64(0.07680165565180293),
 np.float64(-0.09664893126920143),
 np.float64(0.04890933820075096),
 np.float64(-0.025100101595653665),
 np.float64(-0.012956697431970993),
 np.float64(0.020162459503185466),
 np.float64(0.43575911536162676),
 np.float64(-0.06158163174213888),
 np.float64(-0.027467537687839383),
 np.float64(-0.08059359295829101),
 np.float64(-0.11174761314223837),
 np.float64(0.4502956016056707),
 np.float64(-0.244235228692593),
 np.float64(0.029794520547937405),
 np.float64(0.13393865228661098),
 np.float64(0.08919280511372082),
 np.float64(-0.7381849490293995),
 np.float64(0.32468994728501593),
 np.float64(-0.1819388787380956),
 np.float64(-0.05695672961988307),
 np.float64(-0.3406643874977947),
 np.float64(0.08702109147639549),
 np.float64(-0.20053953828842105),
 np.float64(-0.8293008417208483),
 np.float64(0.19683796274073084),
 np.float64(0.1753219273320839),
 np.float64(0.12614665057332616),
 np.float64(-0.13501375226574597),
 np.float64(0.28063795757009574),
 np.float64(0.09089679369495683),
 np.float64(0.2309366750651077),
 np.float64(0.0017998014818921815),
 np.float64(0.6857421221470267),
 np.float64(0.005839203818598361),
 np.float64(-1.0819174587362206),
 np.float64(0.625101547191462),
 np.float64(-0.09450034904522352),
 np.float64(0.1977172346967984),
 np.float64(0.3228689683874692),
 np.float64(-0.17255252570407228),
 np.float64(-0.08629105206121974),
 np.float64(0.2443812335291437),
 np.float64(-0.14004475113107512),
 np.float64(0.6178401934155229),
 np.float64(1.1421833283891987),
 np.float64(0.20743492526622956),
 np.float64(0.580844766931111),
 np.float64(1.8501371048541593),
 np.float64(-0.7142857142857143),
 np.float64(0.3133813400548523),
 np.float64(-0.18220597896089497),
 np.float64(2.6668048075915687),
 np.float64(-0.1879725031078984),
 np.float64(-0.31181147941898474),
 np.float64(0.272668601867263),
 np.float64(0.000266540186337302),
 np.float64(-0.5246479609236312),
 np.float64(0.4228599037004872),
 np.float64(-0.006263176719732603),
 np.float64(-0.45940329533951124),
 np.float64(0.05318976329849487),
 np.float64(0.10436289351305765),
 np.float64(0.09294264179668624),
 np.float64(0.10415729905387956),
 np.float64(0.309278785322656),
 np.float64(-1.0568606947247041),
 np.float64(-0.5421276470368276),
 np.float64(-0.5500674303311316),
 np.float64(-0.22766265198275906),
 np.float64(0.2713008719636857),
 np.float64(-0.03909412149525019),
 np.float64(-0.7786796857613962),
 np.float64(0.6365211783796255),
 np.float64(0.0010899651497909867),
 np.float64(0.70914377704716),
 np.float64(-0.10519463856237207),
 np.float64(-0.040385845196054176),
 np.float64(0.05644609241300877),
 np.float64(-0.22314846000340682),
 np.float64(-0.06755423802489866),
 np.float64(-0.5085216762832334),
 np.float64(0.42837662142669625),
 np.float64(-0.06300598642709361),
 np.float64(-0.19910075402897262),
 np.float64(0.4235386932510996),
 np.float64(-0.032595222471666914),
 np.float64(0.2894090297617686),
 np.float64(-0.646630574155856),
 np.float64(-0.1322986904637893),
 np.float64(-0.08185931053813962),
 np.float64(0.7584044578518249),
 np.float64(0.4867315138081588),
 np.float64(-0.32078226532940646),
 np.float64(-0.5216441380284362),
 np.float64(-0.4135491598476548),
 np.float64(0.09036343723139671),
 np.float64(-0.2806965444470437),
 np.float64(0.08028280283321251),
 np.float64(-0.5129517105369068),
 np.float64(0.03664959630483628),
 np.float64(0.48172080694416236),
 np.float64(-0.02395690002604925),
 np.float64(0.03268418314369225),
 np.float64(-0.08590643809119146),
 np.float64(0.1495691481196728),
 np.float64(-0.10224299065420643),
 np.float64(0.11875549537419892),
 np.float64(0.24818361907609598),
 np.float64(-0.06605094641713434),
 np.float64(-0.06160315428814572),
 np.float64(-0.15484230393975812),
 np.float64(0.6406640932726387),
 np.float64(-0.7918954850568859),
 np.float64(-2.005501196698244),
 np.float64(-0.4225842324388109),
 np.float64(0.4832275550409804),
 np.float64(-0.37195199070921536),
 np.float64(-0.2706022961606688),
 np.float64(-0.3639750588600588),
 np.float64(-0.28648354689394084),
 np.float64(0.8971877670201739),
 np.float64(0.2800470599409622),
 np.float64(-0.45050371524740956),
 np.float64(0.41835533477290926),
 np.float64(-0.17310664787789654),
 np.float64(-0.16208809793199944),
 np.float64(0.34891199714918497),
 np.float64(-0.12731989200096105),
 np.float64(-0.2704301828364412),
 np.float64(-0.6029399971022589),
 np.float64(-0.6136405072274311),
 np.float64(0.40205116060651874),
 np.float64(0.05095603619814538),
 np.float64(0.2755016918402483),
 np.float64(-0.0323857796446128),
 np.float64(-0.005107386513185411),
 np.float64(0.20786933927245732),
 np.float64(-0.6117647058823599),
 np.float64(1.1812671742615077),
 np.float64(0.6733069601672286),
 np.float64(0.09933194255928865),
 np.float64(0.7671689695869438),
 np.float64(0.07459479255507251),
 np.float64(0.2110324671022102),
 np.float64(-0.4036982474964394),
 np.float64(0.05671371890913485),
 np.float64(-0.12776585861052595),
 np.float64(-0.3460051171715921),
 np.float64(-0.02786287787934881),
 np.float64(0.12050042258322342),
 np.float64(0.29698258869070726),
 np.float64(-0.0862720115691906),
 np.float64(0.038584690851252504),
 np.float64(-0.09618464194698438),
 np.float64(-0.0841261726695329),
 np.float64(0.1362211895388285),
 np.float64(0.1785497934445483),
 np.float64(0.3173497448846653),
 np.float64(0.423646944284321),
 np.float64(-0.40832708825733804),
 np.float64(0.016815069543784728),
 np.float64(-0.1306927409753237),
 np.float64(-0.006287486785790481),
 np.float64(-0.13220489513073075),
 np.float64(0.009038103512827834),
 np.float64(0.18644665004559818),
 np.float64(0.21436281539966673),
 np.float64(-0.08362566678031084),
 np.float64(-0.0799793855339144),
 np.float64(0.05645441389290124),
 np.float64(-0.014492539813269083),
 np.float64(0.23373696042716918),
 np.float64(-0.19419672751958952),
 np.float64(0.007851812156322448),
 np.float64(-0.3722160787861091),
 np.float64(0.24616858237547218),
 np.float64(-0.14422293199631836),
 np.float64(0.2401050018999924),
 np.float64(-0.049118023407416576),
 np.float64(0.3393500154256509),
 np.float64(-0.25934465683379115),
 np.float64(-0.10667966834163489),
 np.float64(0.19740458850595888),
 np.float64(-0.12715439811633159),
 np.float64(-0.2049471099333207),
 np.float64(0.2071653138040584),
 np.float64(0.21836622374835912),
 np.float64(-0.6337686764536655),
 np.float64(-0.057169433293468574),
 np.float64(-0.04428224898018019),
 np.float64(0.03201598647477828),
 np.float64(0.15027583515442833),
 np.float64(-0.2651388107401788),
 np.float64(-0.2951505983991783),
 np.float64(0.06126855387822929),
 np.float64(-0.07634187918000086),
 np.float64(0.45840122719106946),
 np.float64(0.3665848514102722),
 np.float64(0.054043473942882926),
 np.float64(-0.34424162518047474),
 np.float64(-0.15015950272840814),
 np.float64(-0.3568271048422269),
 np.float64(-0.19171217343845842),
 np.float64(0.36572333255792233),
 np.float64(-0.02820374760209958),
 np.float64(-0.04173466400462378),
 np.float64(-0.025613977388568243),
 np.float64(-0.2092951668462907),
 np.float64(0.2734887467183886),
 np.float64(0.43398979006997124),
 np.float64(0.8426674467100838),
 np.float64(1.2573381294964112),
 np.float64(-0.3021576477402254),
 np.float64(0.032496588927112796),
 np.float64(-0.28282799498461186),
 np.float64(-1.036614875454913),
 np.float64(0.5775193250016253),
 np.float64(0.20815389032443296),
 np.float64(-0.3057516931807517),
 np.float64(-0.22295797523810493),
 np.float64(-0.08499860951951235),
 np.float64(-1.1001997768725746),
 np.float64(0.09602981077798636),
 np.float64(-0.9168752305073804),
 np.float64(-0.3717985078684581),
 np.float64(0.3722715719568682),
 np.float64(-0.11296160583878709),
 np.float64(-0.41014941419940776),
 np.float64(0.6883622347088176),
 np.float64(0.25856807511737856),
 np.float64(0.3742816403126503),
 np.float64(-0.29469904730886215),
 np.float64(-0.26501000806112174),
 np.float64(-0.6108317069509074),
 np.float64(0.2610927543072929),
 np.float64(0.5959923782889763),
 np.float64(-0.9665358568627184),
 np.float64(0.10256490534639631),
 np.float64(0.14273557787918686),
 np.float64(0.802702792687379),
 np.float64(-0.14383783066478487),
 np.float64(0.11066088300974271),
 np.float64(0.3127564363748221),
 np.float64(-0.31625558056290287),
 np.float64(0.14269339633676492),
 np.float64(0.10805012089028096),
 np.float64(0.16712848184338022),
 np.float64(0.210847846533273),
 np.float64(0.020514486467333285),
 np.float64(-0.3759249416757144),
 np.float64(-0.10409024050838062),
 np.float64(-0.8267297512367124),
 np.float64(-0.1096150243226672),
 np.float64(0.04907737915892138),
 np.float64(0.12395126655014961),
 np.float64(-0.3328582627713788),
 np.float64(0.19857271434408608),
 np.float64(-0.026731218263113213),
 np.float64(-0.36090164421062887),
 np.float64(-0.37832477588158875),
 np.float64(0.2612826850094211),
 np.float64(0.0828063813907421),
 np.float64(-0.3228610914890829),
 np.float64(-0.18702289056906676),
 np.float64(0.3255395902702581),
 np.float64(0.3180819183187735),
 np.float64(-0.030147523457023595),
 np.float64(-0.040765360407004236),
 np.float64(-0.10259797101094179),
 np.float64(0.3211015079386022),
 np.float64(0.21991150442478732),
 np.float64(0.24884799815626213),
 np.float64(0.06576803262564618),
 np.float64(-0.042339685753268755),
 np.float64(-0.44453491957702346),
 np.float64(-0.3636672424092609),
 np.float64(0.15445833272298604),
 np.float64(0.08417916304223896),
 np.float64(0.2895228850614508),
 np.float64(-0.18408326621735305),
 np.float64(0.4664463974451274),
 np.float64(0.7201320234704606),
 np.float64(-0.38527342988945906),
 np.float64(0.25038180445758745),
 np.float64(0.21191940496217382),
 np.float64(0.9306016657930075),
 np.float64(0.06496419971982849),
 np.float64(-1.0194761745688778),
 np.float64(-0.2578619265401563),
 np.float64(-0.08649747159553367),
 np.float64(-0.14882320484385328),
 np.float64(0.05451224205309914),
 np.float64(0.15775651307047273),
 np.float64(-0.02922874244393882),
 np.float64(0.1461134053350972),
 np.float64(-0.006098629427882272),
 np.float64(-0.028043733633557645),
 np.float64(-0.10781330477771202),
 np.float64(-0.2494348558911761),
 np.float64(-0.14209339114130942),
 np.float64(-0.0572057205720572),
 np.float64(-0.2729980813375993),
 np.float64(0.5641353936718201),
 np.float64(0.024000001170723248),
 np.float64(0.4299358607561444),
 np.float64(-0.8234563489467845),
 np.float64(-0.8469360445627813),
 np.float64(-0.4239593160237497),
 np.float64(-0.023164272330919385),
 np.float64(0.21244044457732866),
 np.float64(0.10707905243577089),
 np.float64(0.3947496457755251),
 np.float64(0.041429647907084116),
 np.float64(-0.2128667014035203),
 np.float64(-0.08198042445405376),
 np.float64(0.04516400057353494),
 np.float64(0.1712318372472979),
 np.float64(-0.14139245703907624),
 np.float64(0.2502220248667894),
 np.float64(-0.020286715966051846),
 np.float64(-0.052130013138835085),
 np.float64(0.009367610909057283),
 np.float64(0.010297497205863758),
 np.float64(-0.09046682892788421),
 np.float64(0.10635486981249134),
 np.float64(0.003973177360277573),
 np.float64(-0.11721146019691789),
 np.float64(0.04915172608471344),
 np.float64(0.08452485694398934),
 np.float64(0.003322614333374288),
 np.float64(0.12305077923054315),
 np.float64(-0.16525737010262315),
 np.float64(0.012896786705755788),
 np.float64(0.13443129476643995),
 np.float64(-0.059462152951818205),
 np.float64(0.004516558500499142),
 np.float64(0.0631404072630048),
 np.float64(-0.05388180576766726),
 np.float64(0.007954544280615393),
 np.float64(0.002124977920154734),
 np.float64(0.18026515623275852),
 np.float64(-0.1973663181614651),
 np.float64(-0.03208619290090065),
 np.float64(0.08300207062262799),
 np.float64(0.09314129567006477),
 np.float64(-0.18307325494579454),
 np.float64(0.16637036068024189),
 np.float64(-0.1770166133828282),
 np.float64(0.043797338521684034),
 np.float64(-0.32573842801280783),
 np.float64(-1.480823337000046e-05),
 np.float64(1.0684436546720035),
 np.float64(-0.4637844748681731),
 np.float64(0.3400162419984027),
 np.float64(0.12694017264039348),
 np.float64(-0.1616643842109199),
 np.float64(-0.056572889214856883),
 np.float64(-0.3294244374345476),
 np.float64(-0.2683146121047039),
 np.float64(0.05880602932413049),
 np.float64(0.13914119251014403),
 np.float64(-0.022216911654689607),
 np.float64(0.16494600915740926),
 np.float64(-0.23903250500529288),
 np.float64(0.08613512279531996),
 np.float64(0.9613263741448377),
 np.float64(-0.08751970215553304),
 np.float64(-0.048643528152513306),
 np.float64(0.18601168714939587),
 np.float64(0.27733177638300976),
 np.float64(0.4933770732717677),
 np.float64(-0.191544076429918),

In [7]:
#data   : range ema int
#period : price list
#--return list
Get_ema(data=df["close"],period=14)

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 62999.78357142857,
 62741.66176190476,
 62499.84286031746,
 62309.4024789418,
 62052.644815082895,
 61874.56817307184,
 61720.221749995595,
 61559.78151666285,
 61446.47731444114,
 61367.481672515656,
 61291.816116180235,
 61223.57263402287,
 61177.32161615315,
 61139.70940066606,
 61085.33481391059,
 61042.758172055845,
 61026.6570824484,
 61016.83747145528,
 61017.061808594575,
 60986.78690078197,
 60975.80598067771,
 60945.16384992068,
 60910.34333659792,
 60883.63222505153,
 60895.41459504466,
 60888.027315705374,
 60926.18100694466,
 60962.84887268537,
 60981.00902299399,
 61012.14648659479,
 61029.72695504882,
 61027.97402770898,
 61013.517490681115,
 60999.713825256964,
 60976.55064855603,
 60976.74389541523,
 60962.243376026534,
 60957.92425922299,
 60954.201024659924,
 60973.6408880386,
 60983.82343630012,
 60978.84564479344,
 60957.66622548764,
 60969.973395422625,
 60973.976942699606,
 60998.778683672994,
 61018.408192516596,
 61036.72043351438,
 61057.3297090458,
 61072.19508117303,
 61118.435737016625,
 61148.88030541441,
 61211.202931359156,
 61232.901207177936,
 61255.99437955421,
 61259.73246228032,
 61256.56813397628,
 61265.82571611278,
 61294.91428729774,
 61323.97771565804,
 61336.230020236966,
 61297.30068420537,
 61280.327259644655,
 61239.87829169203,
 61189.09051946643,
 61231.09178353757,
 61378.19554573256,
 61563.39347296822,
 61763.021009905795,
 61884.57820858502,
 61998.36778077369,
 62111.12407667053,
 62200.26219978113,
 62273.276573143645,
 62370.43969672449,
 62478.233070494556,
 62522.536661095284,
 62557.78510628258,
 62639.772425444906,
 62700.05476871892,
 62726.947466223064,
 62732.68780405999,
 62760.34009685199,
 62767.63208393839,
 62752.217139413275,
 62724.18685415817,
 62692.75660693708,
 62673.75172601214,
 62679.54749587719,
 62594.54116309356,
 62519.98767468109,
 62432.12265139028,
 62347.55296453824,
 62263.747235933144,
 62201.72360447539,
 62117.02979054533,
 62060.88981847262,
 62026.6031760096,
 61994.73741920832,
 61919.11109664721,
 61838.56028376092,
 61784.084245926126,
 61759.07567980264,
 61739.204255828954,
 61733.25168838509,
 61729.99012993374,
 61709.65677927591,
 61673.48254203912,
 61676.484869767235,
 61689.48822046494,
 61724.22179106961,
 61747.658885593664,
 61771.795034181174,
 61797.25569629035,
 61850.29360345163,
 61889.389122991415,
 61990.801239925895,
 62081.98907460244,
 62133.34786465545,
 62349.90948270139,
 62589.38688500787,
 62844.13530034015,
 63094.931926961464,
 63316.84367003327,
 63547.47251402883,
 63836.780178824985,
 64126.04015498165,
 64366.68413431743,
 64565.79158307511,
 64772.52603866509,
 64963.72256684308,
 65113.079557930665,
 65229.46761687324,
 65320.139934623476,
 65407.50661000701,
 65461.616395339406,
 65504.33287596082,
 65564.84049249938,
 65641.87776016613,
 65729.24339214398,
 65813.96960652478,
 65861.43899232148,
 65947.08712667861,
 65955.6101764548,
 66005.26881959416,
 65951.05964364827,
 65933.43569116184,
 65829.64293234026,
 65718.35587469488,
 65638.8657580689,
 65578.59699032638,
 65537.97072494953,
 65527.83996162292,
 65513.32396673987,
 65476.24210450788,
 65480.568490573496,
 65461.9380251637,
 65451.8142884752,
 65469.509716678505,
 65467.1497544547,
 65498.19645386074,
 65559.17826001265,
 65669.54649201097,
 65733.07495974284,
 65814.59029844379,
 65906.04225865129,
 65947.63662416444,
 66005.28107427584,
 65997.11293103907,
 66105.05254023385,
 66250.392201536,
 66341.00524133121,
 66389.20720915371,
 66446.91024793322,
 66527.05421487546,
 66575.4469862254,
 66606.80738806202,
 66628.77973632042,
 66681.4757714777,
 66709.49100194733,
 66745.55886835436,
 66767.19635257378,
 66790.91017223061,
 66803.27014926652,
 66810.12879603099,
 66824.78228989353,
 66833.0779845744,
 66859.01291996447,
 66894.48319730254,
 66938.1814376622,
 66971.86657930724,
 66968.68436873294,
 66954.61578623521,
 66933.15501473719,
 66918.5516794389,
 66914.50078884704,
 66908.10201700077,
 66893.20308140067,
 66895.79200388058,
 66904.8877366965,
 66904.14137180363,
 66907.85718889648,
 66908.83623037695,
 66908.52873299336,
 66910.05956859425,
 66950.26629278169,
 66979.5921204108,
 67002.54650435603,
 67015.22297044189,
 67016.21324104963,
 67057.310142243,
 67071.0034566106,
 67085.53766239586,
 67110.13130740974,
 67139.44713308844,
 67098.58618200998,
 67092.10669107531,
 67070.22579893193,
 67046.17969240768,
 66994.95706675333,
 66958.29745785288,
 66908.68579680583,
 66792.06235723173,
 66708.3193762675,
 66651.2101260985,
 66612.86344261869,
 66567.68298360286,
 66553.32391912249,
 66548.93406323949,
 66565.61218814089,
 66580.22656305543,
 66653.85368798138,
 66718.1878629172,
 66677.09614786158,
 66696.8353281467,
 66705.52395106047,
 66730.65542425241,
 66781.23336768543,
 66809.6289186607,
 66826.5303961726,
 66862.9903433496,
 66882.05963090298,
 66953.78368011591,
 67118.62052276713,
 67280.3391197315,
 67473.41523710063,
 67810.29187215389,
 68035.58628920003,
 68259.88011730669,
 68437.3321016658,
 68838.57048811036,
 69168.40375636231,
 69424.611255514,
 69672.50308811213,
 69887.36934303051,
 70023.72009729312,
 70181.8720843207,
 70318.34380641127,
 70393.00329888977,
 70462.73619237114,
 70533.04070005499,
 70602.76860671432,
 70673.06612581908,
 70763.32264237654,
 70741.00229005967,
 70670.62865138505,
 70558.14349786704,
 70439.46169815144,
 70361.80680506458,
 70290.86456438931,
 70156.8812891374,
 70099.56511725241,
 70049.99110161875,
 70072.95495473625,
 70083.00629410475,
 70087.94012155745,
 70097.49210534978,
 70084.89449130314,
 70067.67122579606,
 70005.31239568992,
 69991.0200762646,
 69972.76139942932,
 69938.39321283874,
 69947.97678446025,
 69953.23854653221,
 69984.80674032791,
 69951.64984161753,
 69910.61386273519,
 69867.4480143705,
 69900.40561245443,
 69974.47153079383,
 70008.52599335465,
 69989.19186090736,
 69933.91294611972,
 69894.38721997042,
 69834.0702573077,
 69789.230223,
 69702.83685993333,
 69631.34127860889,
 69613.80377479437,
 69596.3846048218,
 69584.31465751222,
 69565.89136984393,
 69563.77385386474,
 69552.45600668277,
 69553.64853912506,
 69577.70073390838,
 69592.40596938727,
 69599.4265068023,
 69591.130972562,
 69643.34284288707,
 69614.70113050213,
 69404.22631310184,
 69183.4801380216,
 69035.81611961871,
 68874.07797033622,
 68709.43424095806,
 68533.91767549698,
 68356.05931876405,
 68282.30340959551,
 68243.69895498277,
 68169.40176098507,
 68142.76819285372,
 68103.99910047323,
 68055.7338870768,
 68045.41870213323,
 68024.94020851547,
 67982.71218071341,
 67891.6825566183,
 67757.72621573585,
 67677.4867203044,
 67612.50849093047,
 67580.87535880641,
 67550.54931096555,
 67523.80806950347,
 67519.30032690302,
 67460.34294998262,
 67514.8945566516,
 67623.10328243139,
 67725.93351144054,
 67885.01170991514,
 68029.73414859312,
 68174.56692878071,
 68262.88600494328,
 68344.63453761752,
 68403.74859926851,
 68423.24745269938,
 68437.59979233946,
 68461.04782002754,
 68508.53744402387,
 68541.77911815402,
 68574.12456906681,
 68593.33595985791,
 68602.27783187685,
 68622.4967876266,
 68656.38921594305,
 68714.90665381732,
 68804.65109997502,
 68844.65361997834,
 68880.87313731457,
 68900.22071900596,
 68916.41128980517,
 68918.27645116448,
 68920.72225767588,
 68939.97795665242,
 68976.4075624321,
 69000.26255410782,
 69013.5622135601,
 69030.28858508542,
 69043.45010707404,
 69076.39942613084,
 69087.01283598006,
 69096.93645784938,
 69071.21293013613,
 69071.53387278464,
 69058.52935641336,
 69069.33877555825,
 69074.17760548381,
 69109.6405914193,
 69116.39917923007,
 69112.41795533273,
 69127.15156128837,
 69128.18601978326,
 69110.19055047883,
 69113.65047708165,
 69136.7797468041,
 69098.27444723021,
 69059.65385426619,
 69022.11867369736,
 68992.52418387105,
 68980.65962602157,
 68946.0170092187,
 68888.95074132287,
 68845.09064247982,
 68800.1012234825,
 68802.98239368484,
 68839.1194078602,
 68875.4168201455,
 68875.15191079277,
 68861.13298935373,
 68816.2632574399,
 68759.85882311458,
 68744.3256466993,
 68728.2822271394,
 68710.56059685415,
 68692.85785060693,
 68658.37813719267,
 68653.45038556699,
 68688.88900082473,
 68797.03713404809,
 69007.27884950835,
 69161.1376695739,
 69297.52064696405,
 69389.25122736885,
 69372.01906371966,
 69410.41785522371,
 69463.02880786055,
 69480.16896681247,
 69474.3371045708,
 69461.41349062804,
 69348.43969187763,
 69259.31439962728,
 69098.11247967699,
 68924.66948238671,
 68808.00288473515,
 68696.6425001038,
 68562.95683342329,
 68509.22792230018,
 68486.1628659935,
 68500.27581719436,
 68485.55504156844,
 68448.63170269266,
 68361.0808090003,
 68308.80336780025,
 68317.50691876022,
 68236.93532959219,
 68176.3666189799,
 68136.77506978258,
 68175.11039381157,
 68195.21034130336,
 68222.71162912958,
 68275.07007857897,
 68291.51273476843,
 68318.77770346598,
 68352.27400967052,
 68396.58414171445,
 68454.29558948586,
 68506.19351088775,
 68516.66504276938,
 68516.22037040013,
 68440.31098768012,
 68364.59085598943,
 68303.40807519083,
 68261.60566516539,
 68195.20357647668,
 68155.59643294645,
 68118.84890855358,
 68054.33705407978,
 67964.30944686914,
 67909.75885395326,
 67869.94034009283,
 67806.32562808045,
 67734.38621100306,
 67701.23604953599,
 67701.1272429312,
 67698.31161054036,
 67692.19272913499,
 67677.63369858365,
 67693.94920543916,
 67727.9693113806,
 67780.00006986319,
 67831.06672721477,
 67871.47649691947,
 67866.11296399687,
 67828.57256879729,
 67809.95755962432,
 67801.42188500775,
 67820.17630034004,
 67819.75412696137,
 67861.56557669985,
 67963.2221664732,
 68016.07254427677,
 68084.6975383732,
 68163.53786659011,
 68317.07948437809,
 68456.15288646102,
 68482.40183493288,
 68481.5469236085,
 68472.90866712737,
 68451.84484484371,
 68438.55486553122,
 68441.41421679372,
 68441.22565455457,
 68454.3942339473,
 68465.249669421,
 68472.09504683153,
 68468.17837392066,
 68442.02125739791,
 68406.41708974485,
 68370.36147777888,
 68314.3132807417,
 68316.84884330948,
 68321.23299753488,
 68364.2139311969,
 68326.0974070373,
 68216.18575276567,
 68082.77165239691,
 67965.07009874399,
 67882.09675224479,
 67819.80118527882,
 67801.29436057498,
 67788.99377916497,
 67759.11594194298,
 67725.83648301725,
 67701.05961861495,
 67695.00633613295,
 67677.00549131523,
 67683.94475913986,
 67688.12679125454,
 67687.0445524206,
 67686.95194543118,
 67687.80101937368,
 67680.37155012386,
 67683.52201010735,
 67686.61107542636,
 67678.70693203618,
 67676.28867443136,
 67681.81818450718,
 67686.9104265729,
 67702.43436969651,
 67700.94712040364,
 67700.82217101648,
 67712.84854821429,
 67717.89674178572,
 67722.67850954762,
 67732.5267082746,
 67736.19114717132,
 67740.08566088181,
 67743.6542394309,
 67763.03367417345,
 67761.962517617,
 67758.13551526806,
 67762.31344656565,
 67774.3543203569,
 67768.22707764264,
 67777.94213395695,
 67770.34984942936,
 67767.72586950545,
 67736.02775357138,
 67708.5560530952,
 67780.95124601584,
 67801.48974654707,
 67850.08844700747,
 67903.7433207398,
 67935.53354464116,
 67957.94640535567,
 67947.45755130825,
 67914.08187780049,
 67890.46429409376,
 67882.56238821459,
 67873.70606978597,
 67880.94392714785,
 67865.56873686147,
 67860.02490527995,
 67942.15625124262,
 68005.34608441027,
 68055.6746064889,
 68116.25132562371,
 68194.08448220722,
 68306.7318845796,
 68386.72763330232,
 68487.50394886201,
 68557.82075568041,
 68604.50998825635,
 68667.90865648884,
 68811.68483562366,
 68942.8388575405,
 68920.59500986843,
 69013.2196752193,
 69022.12638519006,
 69055.03886716472,
 69086.15501820942,
 69101.86768244817,
 69101.7893247884,
 69099.04008148328,
 69091.50273728551,
 69053.95570564744,
 69046.94961156113,
 69069.40966335297,
 69078.7643749059,
 69090.95845825179,
 69086.99333048488,
 69069.52888642023,
 69047.64903489753,
 69043.11316357786,
 69015.57007510081,
 68975.8833984207,
 68964.52027863127,
 68963.36424148043,
 68961.12367594971,
 69036.70585248974,
 69118.67707215778,
 69295.5201292034,
 69496.11744530962,
 69638.501785935,
 69779.19088114367,
 69865.11209699119,
 69936.7891507257,
 70027.88393062894,
 70099.00607321176,
 70157.5172634502,
 70239.9816283235,
 70339.49074454703,
 70405.95331194076,
 70478.17020368199,
 70570.21817652439,
 70627.52108632114,
 70693.05827481166,
 70760.65050483677,
 70782.9064375252,
 70797.74424585518,
 70798.0890130745,
 70821.2384779979,
 70837.07468093152,
 70822.89139014065,
 70828.90453812189,
 70929.05059970563,
 70980.21318641155,
 71066.71542822334,
 71070.72803779355,
 71098.62429942108,
 71111.6103928316,
 71115.18500712072,
 71119.14167283796,
 71117.65611645956,
 71104.37663426495,
 71106.99308302962,
 71114.060671959,
 71105.51924903113,
 71098.71934916031,
 71071.61676927227,
 71047.13320003597,
 71043.71144003117,
 71025.08458136035,
 71018.9239705123,
 71014.800774444,
 71035.49533785146,
 71055.71862613794,
 71064.7014759862,
 71118.01727918805,
 71142.28164196297,
 71116.50408970124,
 71114.0782110744,
 71108.86778293115,
 71024.950745207,
 70984.2919791794,
 70951.78771528881,
 70945.0173532503,
 70925.55637281692,
 70919.88885644134,
 70909.23834224915,
 70897.88389661594,
 70910.12337706714,
 70952.3095934582,
 70997.4149809971,
 71033.18631686416,
 71043.42814128227,
 71053.26438911131,
 71086.43847056314,
 71125.23067448805,
 71201.86525122297,
 71206.16188439324,
 71249.9536331408,
 71274.08514872204,
 71252.41246222577,
 71201.88680059566,
 71015.4472271829,
 70767.31159689184,
 70565.6700506396,
 70397.97937722098,
 70244.91679359152,
 70145.46122111265,
 70040.14639163096,
 69954.9935394135,
 69889.69440082503,
 69827.34981404836,
 69774.63650550858,
 69713.5823047741,
 69661.10333080422,
 69617.41622003033,
 69612.72072402628,
 69589.21396082277,
 69569.7507660464,
 69554.23733057355,
 69529.12968649708,
 69506.60839496413,
 69496.39394230225,
 69491.76674999528,
 69483.53251666257,
 69470.68151444089,
 69466.58931251544,
 69465.02940418005,
 69464.36015028937,
 69452.14279691745,
 69445.8450906618,
 69431.48574524022,
 69415.3489792082,
 69395.79578198044,
 69381.02301104972,
 69353.54394290976,
 69340.98875052179,
 69336.11558378555,
 69330.42950594747,
 69338.50690515447,
 69332.79131780054,
 69335.37247542714,
 69339.98681203685,
 69340.85390376527,
 69344.43204992989,
 69393.56777660591,
 69403.36273972513,
 69414.93037442844,
 69427.42499117131,
 69453.48565901513,
 69481.08890447978,
 69515.35705054914,
 69541.34411047591,
 69560.7448957458,
 69585.97357631303,
 69592.42376613796,
 69599.85259731956,
 69594.53758434362,
 69598.6685730978,
 69614.31276335144,
 69614.16439490458,
 69622.18647558398,
 69616.62561217278,
 69591.72486388308,
 69553.36021536533,
 69531.24551998329,
 69520.41145065219,
 69509.68859056523,
 69504.91544515653,
 69486.12538580233,
 69475.73666769535,
 69500.5837786693,
 69575.98860818007,
 69628.81279375605,
 69684.03775458857,
 69707.50072064342,
 69678.6072912243,
 69672.46098572772,
 69660.86352096403,
 69638.8803848355,
 69625.6963335241,
 69597.05015572089,
 69480.64480162477,
 69319.04149474147,
 69205.03596210928,
 69047.56983382803,
 68895.03652265096,
 68734.63165296416,
 68579.37143256894,
 68437.68724155975,
 68257.24094268511,
 68084.54081699376,
 67925.27004139459,
 67804.56603587531,
 67672.2238977586,
 67562.76204472412,
 67386.99110542757,
 67267.05495803723,
 67200.91296363226,
 67189.76456848129,
 67218.73062601712,
 67228.24254254816,
 67250.69153687508,
 67265.2953319584,
 67271.82128769728,
 67262.24378267098,
 67251.27927831485,
 67273.1420412062,
 67290.98976904538,
 67316.40313317266,
 67306.64404874964,
 67303.31017558303,
 67323.35281883863,
 67332.70044299348,
 67388.78305059434,
 67469.2093105151,
 67510.43873577975,
 67754.28557100912,
 67963.04749487457,
 68229.3838288913,
 68429.99931837246,
 68588.13274258947,
 68749.7137102442,
 68760.15321554498,
 68596.52212013898,
 68530.84850412045,
 68531.53537023773,
 68506.7733208727,
 68474.402211423,
 68455.15124989994,
 68391.74841657994,
 68304.15662770261,
 68193.59441067559,
 68078.18315591884,
 68014.964068463,
 67948.77819266793,
 67918.91576697887,
 67871.80166471502,
 67811.54277608635,
 67812.72373927484,
 67803.02590737153,
 67795.89445305533,
 67768.44052598128,
 67714.7311225171,
 67548.76830618149,
 67472.39919869062,
 67398.74597219854,
 67327.31184257206,
 67230.87159689578,
 67161.81938397634,
 67136.2421327795,
 67104.20984840891,
 67060.04986862105,
 67015.74055280491,
 66987.79781243093,
 66983.02477077347,
 66951.154801337,
 66919.98616115874,
 66937.65333967091,
 66940.95422771478,
 66936.15766401948,
 66964.94197548355,
 66958.95104541907,
 66947.50957269654,
 66959.308296337,
 66975.84052349206,
 66988.46178702646,
 66987.7308820896,
 66908.30009781099,
 66692.98008476953,
 66522.71740680026,
 66389.66975256024,
 66273.71645221887,
 66206.07559192301,
 66204.73351299994,
 66179.30371126662,
 66161.26188309774,
 66164.50963201805,
 66152.7096810823,
 66161.06172360465,
 66175.30282712403,
 66184.84245017417,
 66191.10612348428,
 66188.10130701971,
 66173.28646608375,
 66179.68960393924,
 66185.99765674735,
 66201.19930251437,
 66217.03272884579,
 66234.49636499968,
 66245.02618299972,
 66241.7586919331,
 66251.66019967535,
 66242.63883971864,
 66243.62166108949,
 66230.49743961089,
 66220.39111432944,
 66197.40829908551,
 66188.00585920743,
 66189.60507797978,
 66194.75773424914,
 66190.38470301592,
 66188.42407594713,
 66182.34886582085,
 66177.50235037807,
 66175.97137032766,
 66187.70852095065,
 66204.28205149056,
 66212.55111129182,
 66220.54562978624,
 66245.8022124814,
 66308.53658415054,
 66333.10903959714,
 66368.35716765086,
 66420.90821196408,
 66433.9897837022,
 66471.16447920857,
 66487.3012153141,
 66499.39705327222,
 66511.47877950259,
 66518.28427556892,
 66518.18637215973,
 66519.09485587176,
 66550.68087508886,
 66567.50609174368,
 66569.69994617786,
 66556.70795335414,
 66528.34955957359,
 66487.50295163045,
 66482.21989141306,
 66464.80657255798,
 66420.48569621691,
 66387.35427005465,
 66361.64170071403,
 66276.36680728549,
 66224.85123298076,
 66170.49773524998,
 66097.76603721666,
 65978.06523225443,
 65910.72053462052,
 65838.35779667112,
 65846.3100904483,
 65947.77274505519,
 66101.60037904783,
 66180.31899517479,
 66209.33512915148,
 66257.69044526463,
 66310.798385896,
 66336.60260110987,
 66258.38758762856,
 66108.46790927809,
 66022.99618804101,
 65953.26336296888,
 65902.72291457302,
 65861.82785929662,
 65813.58414472375,
 65794.77425876058,
 65785.8083575925,
 65743.6899099135,
 65702.6005885917,
 65657.7205101128,
 65600.95110876444,
 65500.02429426251,
 65384.55305502751,
 65294.07931435717,
 65215.00073910955,
 65134.33397389494,
 65073.49077737562,
 64985.317340392205,
 64978.80969500658,
 65010.9710690057,
 65046.84025980494,
 65063.97089183095,
 65074.44677292016,
 65069.26586986414,
 65103.75575388225,
 65143.788320031286,
 65181.357877360446,
 65212.255493712386,
 65263.953427884066,
 65272.344970832855,
 65260.55097472181,
 65266.69751142557,
 65300.471176568826,
 65288.408353026316,
 65275.58190595614,
 65250.866985161985,
 65211.02072047372,
 65172.48462441056,
 65139.12134115582,
 65131.770495668374,
 65110.601096245926,
 65080.12228341313,
 65052.74064562472,
 65046.29255954142,
 65018.2548849359,
 65012.40356694445,
 65023.81775801852,
 65041.78339028272,
 65062.53893824502,
 65079.53241314569,
 65109.72942472626,
 65163.62283476276,
 65203.838456794394,
 65291.17199588847,
 65344.433063103344,
 65394.507321356235,
 65503.17167850874,
 65592.06212137424,
 65643.78583852435,
 65576.9677267211,
 65493.641363158284,
 65405.31984807051,
 ...]

In [8]:

# def Get_ema(data, period):
#     if not isinstance(data, (list, tuple)):
#         data = list(data)
#     # if len(data) < period:
#     #     raise ValueError("Data length must be greater than or equal to the period.")
#     ema = []
#     multiplier = 2 / (period + 1)
#     sma = sum(data[:period]) / period
#     ema.append(sma)
#     # Calculate EMA for the rest of the data
#     for price in data[period:]:
#         ema_value = (price - ema[-1]) * multiplier + ema[-1]
#         ema.append(ema_value)

#     return [None] * (period - 1) + ema

In [9]:
#data            : data list or close price
#short_period    : fast default 12 
#long_period     : slow default 26
#signal_period   : signal period default 9
#--return list
Get_macd(df['close'], short_period=12, long_period=26, signal_period=9)

([None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  -898.855449314593,
  -846.9072561480716,
  -809.5849138535268,
  -768.3966979378165,
  -714.9264239532786,
  -662.4127172821609,
  -608.494767983917,
  -577.5464627732217,
  -537.5891699412168,
  -512.7963146461552,
  -492.4721537779842,
  -468.86237356756465,
  -424.1220343876921,
  -394.7648793677072,
  -340.6080783763464,
  -292.14131887170515,
  -258.9874609250837,
  -220.84791454610968,
  -194.07684072159464,
  -181.05520919843548,
  -176.5300539116506,
  -171.73558690449863,
  -172.7229921051112,
  -159.40209313572996,
  -155.92466980489553,
  -146.4885726675784,
  -137.41426781449263,
  -115.1775415869779,
  -100.43084677526349,
  -95.99066312761715,
  -101.50834644495626,
  -86.32934224692144,
  -77.43936069863412,
  -56.829040560252906,
  -41.149740844310145,
  -27.618668521623476,
  -13.86755865602754,
  -4.728340856418072,
  22.443278113147244,
  37.71388239855878,
  70.74921188258304,
  76.49177245402825,
  82.68469857177843,
  76.8566526689101,
  67.58320755790919,
  66.72699606002425,
  77.89894436157192,
  88.06957115780824,
  87.29488193937868,
  56.049015663527825,
  40.96044219197938,
  13.272922324613319,
  -17.98314506234601,
  9.196781002712669,
  96.619152922598,
  198.53754513421882,
  299.53232484265027,
  344.4617696302448,
  380.7869839837149,
  413.3664882893281,
  429.0452852434246,
  433.90388359499775,
  453.03818277534447,
  476.9774977140769,
  460.91129149554035,
  441.1878388571422,
  451.4824803642987,
  447.9573991478028,
  424.9227925064115,
  391.52333952519257,
  374.4615078216739,
  346.85110967422224,
  308.26266543135716,
  265.7392670595218,
  225.12464705811726,
  195.6652764352766,
  183.67670655772235,
  118.32706683533615,
  65.25145660456474,
  9.012941961031174,
  -40.18889078772918,
  -84.56857296082308,
  -112.02856813392282,
  -150.77724163838866,
  -169.09033635968808,
  -172.9150078779785,
  -175.22772763871035,
  -203.7663231476763,
  -232.7826435817915,
  -243.6888474138541,
  -236.17206867927598,
  -226.51291646638128,
  -209.6215246589345,
  -192.86352224958682,
  -188.01023235906905,
  -193.1647176886181,
  -174.44854844324436,
  -151.57384549095877,
  -117.88644180479605,
  -94.1375478420814,
  -72.17020872209105,
  -51.41904321529728,
  -16.04477914911695,
  7.742291320384538,
  66.69281899512134,
  114.09186125885753,
  133.37257116624824,
  249.8949214222739,
  369.32542465509323,
  486.92760895824176,
  591.4745327403871,
  669.3690794900394,
  745.6871536729304,
  850.4873866803464,
  945.953809843646,
  1003.9577161984416,
  1032.3070135852686,
  1063.2002008417767,
  1082.483464922043,
  1075.4753844730003,
  1049.9181090844504,
  1011.8287553289265,
  975.7112416420714,
  923.3669646322451,
  869.3337337597841,
  831.1449205832469,
  806.4695265493938,
  790.2712032858472,
  773.9644690675559,
  736.8368058587221,
  725.9798981497006,
  669.8896154927861,
  643.6011078215015,
  557.4884467363445,
  501.2323339575305,
  398.48509649312473,
  300.68045065642946,
  230.77253211591596,
  178.5303448592167,
  142.50948196739046,
  127.66829899552977,
  111.15388727688696,
  82.28961727194837,
  80.55345567523182,
  64.88548341939895,
  55.4738757156083,
  63.304281352626276,
  58.130447804964206,
  73.2130517456244,
  104.58212261940935,
  162.37929071005055,
  186.59200883565063,
  219.2648562692484,
  254.81213153753197,
  257.22470182990946,
  269.104240357221,
  240.56821794576535,
  284.28400417102966,
  346.28122694956255,
  369.7599487623811,
  365.7954151540471,
  368.050263009005,
  383.6518644565367,
  378.900049471471,
  364.52925369146396,
  346.00080396421254,
  347.6756561270158,
  334.4631254155247,
  327.3525315485167,
  312.29468699118297,
  299.90663570561446,
  281.88196149948635,
  262.24232260294957,
  249.07733688512235,
  233.2895294209011,
  229.4767511578102,
  231.6482012233755,
  238.46186493602,
  238.57784801645903,
  216.57962566618517,
  190.1093417659431,
  161.65906985815673,
  139.9174714135006,
  126.43744446781056,
  112.70742398935545,
  95.06985895366233,
  89.44213866695645,
  88.11315965410904,
  80.90494920639321,
  76.94563960540108,
  71.62577436695574,
  65.94991670871968,
  61.82678131599096,
  81.15336434087658,
  92.06788535078522,
  98.097348987023,
  97.38530654834176,
  89.73712165707548,
  106.79672470060177,
  105.82853079223423,
  105.45939276383433,
  111.14625735396112,
  119.12227653592709,
  84.36625422509678,
  73.48485493056069,
  54.390711837346316,
  35.77016426474438,
  2.596115149281104,
  -18.797753703562194,
  -46.01861672269297,
  -110.87121747304627,
  -150.04939506978553,
  -169.78022486700502,
  -176.63429123385868,
  -187.13893820237718,
  -178.40042584777984,
  -164.70192840929667,
  -139.8379554485582,
  -118.66831332319998,
  -64.2574733295769,
  -20.582114664139226,
  -44.0722226651269,
  -28.857324686818174,
  -21.644771288585616,
  -5.216534053062787,
  24.943213456863305,
  39.051583005013526,
  45.04849267374084,
  62.283467568908236,
  67.58068758569425,
  103.984826486776,
  192.75166093648295,
  271.3854866627662,
  361.56201124418294,
  529.5293508877949,
  615.2079292309354,
  692.6976652065641,
  735.3823567520594,
  908.489367430142,
  1023.0479727485072,
  1083.4050797899836,
  1133.8099348248652,
  1160.3959615920903,
  1138.1668263061001,
  1131.700730839235,
  1113.3828414468007,
  1060.2480524191342,
  1009.5438381960994,
  964.2182704920706,
  922.981905248249,
  886.0590332737629,
  864.5823782137304,
  777.7494162354706,
  670.3242817370046,
  547.7114922383626,
  432.7250447139086,
  352.783126628201,
  283.95167369350384,
  183.4119122923148,
  137.73236233649368,
  100.43377063506341,
  109.51078544865595,
  109.4808593288326,
  105.94982479815371,
  105.13252053852193,
  90.80417651131575,
  74.77103886594705,
  32.97925251853303,
  23.643815892850398,
  12.547119779934292,
  -7.384560875827447,
  0.6379065406217705,
  5.094849313725717,
  24.68732756258396,
  3.550068896438461,
  -20.40989238212933,
  -43.49715671852755,
  -18.989262318631518,
  27.6522989612713,
  45.8496213433973,
  30.35898080127663,
  -5.1712815129430965,
  -27.934178978350246,
  -61.04227039452235,
  -81.83792867904413,
  -125.63614609649812,
  -156.4978133483819,
  -152.3144721543067,
  -148.6293533024873,
  -142.2375439080206,
  -140.3727639675344,
  -129.0261384988553,
  -124.33933918864932,
  -112.66837859872612,
  -88.46864162829297,
  -72.17404837079812,
  -62.00974825884623,
  -61.943020270744455,
  -25.645577883828082,
  -41.12404236262955,
  -163.8562405456032,
  -281.0819087454147,
  -343.6071825914696,
  -408.8783551763627,
  -469.9977256610873,
  -532.1662612185173,
  -590.211623706884,
  -580.8673165544024,
  -551.779585120923,
  -547.1361535406031,
  -514.6731099544122,
  -492.75906600564485,
  -478.7485863762122,
  -443.460961750563,
  -417.66375200967013,
  -407.3387158649857,
  -427.17341728023894,
  -470.7896258844412,
  -478.1444374588318,
  -475.7280141913943,
  -453.64679352099483,
  -432.9183523288375,
  -412.0189941033168,
  -379.78059100235987,
  -383.13089522809605,
  -318.1814082798519,
  -227.21481413771107,
  -147.94121685669234,
  -42.290720789154875,
  45.066912549111294,
  124.6067459332262,
  163.24625361670041,
  194.77331799986132,
  210.23362977584475,
  200.96482983080205,
  189.88910531738657,
  185.63434559527377,
  196.43971224495908,
  197.93075777112972,
  198.95889021732728,
  192.2193485131429,
  180.13692297837406,
  176.078077639424,
  180.6851010617247,
  199.6720840728085,
  235.62334330857266,
  238.50409235872212,
  238.97084341102163,
  229.40820285755035,
  218.95635395831778,
  200.9931520690734,
  185.12508047986194,
  180.83545082472847,
  187.22488114250882,
  185.48002021036518,
  177.5870377682586,
  172.4904043703864,
  165.7330943934794,
  171.43898436149175,
  163.22076158017444,
  155.35587750273407,
  126.88776744203642,
  116.66782061450067,
  99.38429736655962,
  97.92074727354338,
  92.94832771606161,
  106.70146535374806,
  101.91612913993595,
  91.11911496511311,
  92.50083759207337,
  85.50850246970367,
  67.75281537986302,
  64.47057831085112,
  73.20830621050845,
  44.18950834032148,
  17.809772022199468,
  -5.4925259139126865,
  -21.93013796170999,
  -26.311855230364017,
  -44.01933337269293,
  -73.5704420782422,
  -92.53577861873782,
  -110.51459467048699,
  -98.28951215067354,
  -67.46485191833926,
  -39.566957412462216,
  -36.238100378919626,
  -41.46708019163634,
  -64.66736830482841,
  -92.58773798547918,
  -93.4541502653592,
  -94.61234620811592,
  -96.72543595006573,
  -98.6810995832202,
  -110.5384303546889,
  -103.63852220863919,
  -73.29382469011762,
  -2.355798717602738,
  122.9581053773145,
  202.77534527643002,
  264.81739539367845,
  294.5724216064118,
  256.6539672533545,
  255.92977689407417,
  264.0119664770318,
  250.31052564912534,
  224.34659878225648,
  196.7396862936148,
  111.97826270514634,
  49.549816728933365,
  -50.15850780204346,
  -147.88909245961986,
  -202.6404155678756,
  -249.35953862342285,
  -305.36159185926954,
  -308.5849487607484,
  -293.5339041820116,
  -257.99335467808123,
  -243.33322780544404,
  -243.53223691885069,
  -274.14830118812097,
  -280.8913908442337,
  -250.65932273042563,
  -276.83488961869443,
  -288.6478278973227,
  -286.8947985954146,
  -238.78727081078978,
  -206.2269311412383,
  -172.33496209938312,
  -126.75185288311332,
  -106.90546414804703,
  -82.35145059040224,
  -56.272363608310116,
  -26.05686966383655,
  9.465775103628403,
  38.31461900859722,
  39.835341509533464,
  34.877100260870066,
  -14.590320663410239,
  -59.12279779025994,
  -90.68194314275752,
  -107.65994086173305,
  -137.78731866592716,
  -149.08703268728277,
  -157.6897484283545,
  -182.17529781606572,
  -219.6951408085297,
  -232.54350622075435,
  -235.49737078907492,
  -252.54136871822993,
  -273.0722346887196,
  -268.57724666345166,
  -244.87094839107885,
  -225.13523380855622,
  -209.3080473543523,
  -200.06033093176666,
  -173.22453794049216,
  -138.3312580990023,
  -95.92733505397337,
  -58.03791004657978,
  -29.99328464138671,
  -31.84136120835319,
  -52.605394288373645,
  -59.94581457284221,
  -60.46829981483461,
  -44.54206118886941,
  -41.533731083763996,
  -13.469156430655858,
  47.81242378395109,
  74.18924675797462,
  107.66317647542746,
  144.24835586686095,
  222.25043822919542,
  284.4225490460667,
  273.4839743408229,
  247.67518818324606,
  219.90721967593709,
  187.52243272945634,
  162.9834408741881,
  150.5021972169343,
  137.4128787137597,
  133.56816616895958,
  128.70033535842958,
  121.88661793869687,
  109.26645052507229,
  84.51496379901073,
  56.42095039483684,
  30.656684048037278,
  -4.715965472074458,
  -1.796805233170744,
  1.8190246432641288,
  28.073033524880884,
  3.2313250016595703,
  -62.263362017984036,
  -135.69648305025476,
  -192.9252076989069,
  -224.17568760656286,
  -240.35260847315658,
  -229.0588272891764,
  -215.36325710470555,
  -213.67637724957603,
  -214.33826480183052,
  -209.98198564986524,
  -194.95034830117947,
  -188.58276521260268,
  -167.95935663649288,
  -150.98341707815416,
  -138.7785252067697,
  -127.12901134506683,
  -115.99712428709609,
  -110.83889796775475,
  -99.79722323929309,
  -89.7944612926076,
  -87.26495308603626,
  -81.63704833062366,
  -71.73521926776448,
  -62.98039342914126,
  -48.75606670738489,
  -45.99528575206932,
  -42.6117076731025,
  -32.215095700434176,
  -26.918090927545563,
  -22.217952248756774,
  -14.869661805278156,
  -11.85707343154354,
  -8.93168854121177,
  -6.422265182234696,
  5.361155001388397,
  3.8426248888135888,
  0.8748577078658855,
  3.0237027061812114,
  9.710419411916519,
  4.929352222257876,
  10.11684257540037,
  4.485994931004825,
  2.390077318646945,
  -16.883363287255634,
  -31.791234265823732,
  14.449051825227798,
  25.26227822904184,
  51.872842753640725,
  79.03231247799704,
  90.60919260416995,
  95.57239848531026,
  80.4749398624408,
  53.19966669793939,
  34.39961317364941,
  26.79672664408281,
  19.3333058400749,
  22.18808092708059,
  11.220077580117504,
  7.154547008234658,
  55.90076041192515,
  88.67445170642168,
  110.68729301456187,
  136.81863827862253,
  170.88942287834652,
  222.6735484436067,
  250.15850666775077,
  287.655741667666,
  303.5712877027254,
  304.05439314099203,
  314.6894826650823,
  372.5821655382024,
  417.61133684292145,
  366.81742448230216,
  389.7916820404207,
  360.65058261115337,
  348.7821932279767,
  337.05964093940565,
  317.30060833794414,
  290.00973540703126,
  263.7188265818695,
  237.03120483472594,
  194.86510568998347,
  174.88545415845874,
  174.30931174306897,
  165.82237040060863,
  159.7283580052317,
  144.43842398599372,
  122.42028851239593,
  99.73963777368772,
  89.46460214906256,
  66.26798333035549,
  37.87623943158542,
  28.980186639877502,
  26.8804280521872,
  24.187905762097216,
  68.18461444351124,
  111.72978945665818,
  207.87304863269674,
  309.14912862950587,
  366.14720693322306,
  416.97524883005826,
  430.50188850615814,
  434.5256445087143,
  450.0615713539446,
  452.4220659323473,
  447.24419626093004,
  457.0891793244955,
  476.36956002304214,
  474.213168148417,
  475.8641640512069,
  489.36036694882205,
  480.912772444688,
  478.31146310447366,
  477.2801072042639,
  449.3006675992074,
  419.5964266824303,
  384.05474018999666,
  365.50333635472634,
  344.27470558516507,
  307.0221349755593,
  285.28872911361395,
  321.80849683872657,
  325.4360242947005,
  349.79416091354506,
  322.4396051486692,
  311.9429064138094,
  293.468821576942,
  271.05557765543927,
  250.92012355562474,
  229.34459543120465,
  202.65237715217518,
  187.8812958549097,
  177.0392088458757,
  157.7522266154847,
  141.20416672996362,
  113.94065352357575,
  90.68678245278716,
  82.08244719842332,
  65.03571790001297,
  56.9114061374421,
  50.625162948679645,
  59.6424349466688,
  67.39645221065439,
  67.5916913523979,
  94.2149506075948,
  100.87186369234405,
  76.93386837479193,
  69.2170473325532,
  60.52281948084419,
  5.516312537423801,
  -18.45603692010627,
  -35.39213935070438,
  -35.454417444751016,
  -43.231935410804,
  -42.13270378408197,
  -44.22472796504735,
  -46.63056197615515,
  -34.77381583699025,
  -6.19484019135416,
  21.37848648475483,
  40.75156594342843,
  43.044986420238274,
  44.925643643713556,
  60.63458427586011,
  78.25880175943894,
  116.91038181912154,
  108.6948347796133,
  124.99177274262183,
  128.06644752569264,
  103.5367317856435,
  64.14704872110451,
  -52.79138728356338,
  -195.59305210449384,
  -297.22303961828584,
  -369.23339405651495,
  -426.06916013710725,
  -445.8806673496729,
  -467.76055855781306,
  -475.91078034702514,
  -471.78732698703243,
  -466.62157490171376,
  -456.4677625852637,
  -452.50591233637533,
  -443.9850790948112,
  -431.17582138023863,
  -396.38308873913775,
  -376.2358128666092,
  -355.61927692241443,
  -334.6035946080374,
  -321.30283388186945,
  -307.6759377701237,
  -287.9268204430409,
  -266.644670737267,
  -249.45911560325476,
  -236.57084174494958,
  -219.56207058252767,
  -202.54537442298897,
  -186.49656262366625,
  -178.7598973948625,
  -168.0941921883059,
  -163.1478511610767,
  -159.62216686726606,
  -158.37210462147777,
  -154.28761591471266,
  -158.10976731636038,
  -152.56575753341895,
  -142.88898909911222,
  -134.55421053548343,
  -118.70976339264598,
  -112.55106818508648,
  -101.93532614856667,
  -91.03415701855556,
  -83.32977485664014,
  -74.65278285107343,
  -39.46171751507791,
  -31.058213704658556,
  -22.27839489359758,
  -13.668355712346965,
  2.3463286115584197,
  17.86853053358209,
  36.01568553762627,
  47.60225215861283,
  54.27010632424208,
  63.9101617950364,
  61.51214073317533,
  60.032413226217614,
  51.15704366120917,
  48.84788467253384,
  53.699821252099355,
  48.68866248962877,
  49.08415163595055,
  41.34803456670488,
  22.801298577222042,
  -2.031173193186987,
  -14.801899814541684,
  -19.653814975827117,
  -24.028918706448167,
  -24.478599193913396,
  -33.31890613771975,
  -36.33784854512487,
  -18.036474664360867,
  28.738065836689202,
  57.562699382106075,
  85.14037296461174,
  91.17905884304491,
  65.41849582651048,
  55.794710034911986,
  43.86718885875598,
  26.883550457409,
  16.781685038033174,
  -1.6266902624920476,
  -70.82132401347917,
  -160.55397069572064,
  -213.4417825328419,
  -287.5422415786452,
  -351.93146457376133,
  -415.24562544374203,
  -469.8364281145914,
  -511.5157586616697,
  -572.8347126952867,
  -624.1087112949026,
  -662.9102918353892,
  -675.3870823803882,
  -694.0574216121604,
  -697.6438421315106,
  -740.9074611465912,
  -746.9762514159956,
  -720.6014716963982,
  -664.099618962282,
  -589.152929567048,
  -533.0485668834008,
  -474.51861245167674,
  -426.15709701426385,
  -387.0784499107249,
  -361.1640859417239,
  -338.3388254424499,
  -297.83448943370604,
  -263.3643174674944,
  -227.40627028635936,
  -215.65855502722843,
  -200.9312162341521,
  -173.38288850471145,
  -154.62345352004922,
  -109.45701923269371,
  -53.78443374564813,
  -26.588710828495095,
  119.53453317587264,
  231.1175359351182,
  367.00589951076836,
  451.21477810124634,
  502.63524106414116,
  551.8711565927515,
  506.62030800014327,
  362.0818903506588,
  290.26709714550816,
  265.15799025092565,
  227.29281544461264,
  188.50838714400015,
  161.2408334937354,
  110.08852412678243,
  49.227557823600364,
  -19.746903614199255,
  -85.28259957129194,
  -113.63686165082618,
  -141.37485203619872,
  -145.0435926283244,
  -158.96874730729905,
  -179.68995114629797,
  -161.92485499571194,
  -152.57550781224563,
  -142.74994511507975,
  -146.15271000916255,
  -165.05159749017912,
  -249.42216064492823,
  -272.31816128587525,
  -291.62051892439194,
  -307.96794420899823,
  -337.92552305922436,
  -348.8527939753985,
  -332.9362934797973,
  -322.57429117150605,
  -320.5910210875736,
  -318.9957978470193,
  -307.85337738394446,
  -283.98209779168246,
  -278.63585768046323,
  -273.39460565394256,
  -239.4409796428081,
  -217.2963327150792,
  -202.05153717096255,
  -168.09653738944326,
  -158.08750294648053,
  -152.18301723821787,
  -132.83103536150884,
  -112.38226283290714,
  -96.10151782807952,
  -89.232426809147,
  -129.977470292215,
  -248.05660726279893,
  -327.96104098888463,
  -378.1435911618755,
  -413.5371721673728,
  -416.8994687139202,
  -380.51267006847775,
  -362.186686285655,
  -341.309671227471,
  -309.7653469371289,
  -290.26486098956957,
  -260.563399224513,
  -230.13401010117377,
  -205.34751993216923,
  -184.78673680908105,
  -171.61761342991667,
  -166.64969495986588,
  -149.34560276867705,
  -133.63241825684963,
  -113.97448260505917,
  -95.68345629547548,
  -78.02406581024115,
  -66.0545255063189,
  -63.33873722824501,
  -52.87094028982392,
  -54.59866701568535,
  -50.06433704857773,
  -54.30297497124411,
  -56.246375338334474,
  -65.63808359927498,
  -65.95662330686173,
  -59.62241227085178,
  -51.7266923734569,
  -50.23920023305982,
  -47.40678673009097,
  -47.26553071802482,
  -46.36573719611624,
  -43.53534925506392,
  -33.005611133092316,
  -20.549826437738375,
  -14.203216474837973,
  -8.573556629547966,
  6.900319962966023,
  43.38247034214146,
  53.64350017947436,
  69.41879705851898,
  94.15125134201662,
  93.03347334370483,
  106.55574444652302,
  106.31449537385197,
  103.78355099640612,
  101.57436607395357,
  96.49304607973318,
  87.82496863605047,
  80.62718752049841,
  92.49562468045042,
  94.42860963847488,
  87.45532309974078,
  72.0847387961694,
  48.990808201691834,
  20.6051838532876,
  16.14983504638076,
  4.7962730461295,
  -21.641261547178146,
  -38.94883125365595,
  -50.269362148988876,
  -96.25257738438086,
  -117.78708986357378,
  -139.12396328899194,
  -169.58682465318998,
  -225.4242593441886,
  -244.82721519218467,
  -265.61338042703574,
  -236.59270213037962,
  -154.57874959448236,

In [10]:
#data   : list price
#period : range sma
#--return list
Get_sma(data = df["close"],period=14)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 62999.78,
 62872.86,
 62733.19,
 62601.83,
 62420.94,
 62262.87,
 62116.37,
 61927.15,
 61758.01,
 61601.86,
 61435.65,
 61275.26,
 61102.19,
 60951.29,
 60788.99,
 60767.72,
 60767.29,
 60758.82,
 60804.17,
 60809.37,
 60822.76,
 60839.13,
 60837.27,
 60826.98,
 60839.27,
 60843.56,
 60864.81,
 60886.66,
 60912.89,
 60944.92,
 60960.78,
 60965.32,
 60958.25,
 60966.82,
 60961.22,
 60977.79,
 60990.93,
 61006.64,
 61003.64,
 61022.21,
 61013.34,
 60995.15,
 60975.21,
 60963.46,
 60953.17,
 60963.42,
 60979.59,
 60997.15,
 61023.24,
 61036.87,
 61076.23,
 61106.01,
 61155.03,
 61174.59,
 61200.03,
 61224.14,
 61253.85,
 61273.57,
 61308.14,
 61333.35,
 61352.62,
 61344.66,
 61343.14,
 61329.44,
 61289.43,
 61300.67,
 61351.96,
 61451.48,
 61569.66,
 61668.99,
 61776.28,
 61884.71,
 61977.26,
 62065.47,
 62178.76,
 62331.24,
 62448.42,
 62577.7,
 62742.97,
 62856.38,
 62896.91,
 62897.11,
 62888.5,
 62898.52,
 62892.38,
 62870.81,
 62850.01,
 62835.89,
 62815.55,
 62734.34,
 62678.97,
 62612.84,
 62514.64,
 62416.57,
 62337.77,
 62251.81,
 62162.95,
 62090.71,
 62028.97,
 61949.36,
 61865.54,
 61785.53,
 61705.48,
 61674.62,
 61650.28,
 61639.41,
 61623.67,
 61603.62,
 61596.29,
 61611.11,
 61629.26,
 61636.13,
 61646.21,
 61684.44,
 61747.3,
 61798.27,
 61873.51,
 61949.56,
 62004.75,
 62151.09,
 62334.55,
 62553.24,
 62769.61,
 62982.84,
 63204.02,
 63476.69,
 63767.94,
 64051.38,
 64313.16,
 64596.93,
 64850.97,
 65094.48,
 65345.83,
 65499.54,
 65630.21,
 65724.02,
 65799.51,
 65885.14,
 65963.43,
 66004.85,
 66030.45,
 66047.53,
 66093.52,
 66086.0,
 66094.68,
 66060.02,
 66048.09,
 65994.19,
 65924.16,
 65874.8,
 65832.29,
 65783.41,
 65734.8,
 65672.07,
 65591.39,
 65544.16,
 65461.09,
 65416.45,
 65363.34,
 65352.85,
 65344.35,
 65401.54,
 65500.96,
 65574.09,
 65656.78,
 65744.39,
 65798.39,
 65867.04,
 65917.66,
 66010.38,
 66142.82,
 66253.11,
 66332.96,
 66430.83,
 66527.12,
 66593.86,
 66624.13,
 66668.81,
 66717.35,
 66745.29,
 66799.72,
 66837.42,
 66908.93,
 66914.42,
 66890.11,
 66889.4,
 66902.57,
 66917.26,
 66922.76,
 66946.49,
 66973.65,
 66986.25,
 66974.76,
 66967.77,
 66956.6,
 66955.19,
 66949.58,
 66943.35,
 66947.49,
 66950.63,
 66951.51,
 66944.68,
 66929.69,
 66907.14,
 66887.8,
 66906.63,
 66928.56,
 66954.14,
 66973.71,
 66983.31,
 67016.02,
 67042.0,
 67061.1,
 67082.95,
 67113.72,
 67106.64,
 67116.27,
 67117.81,
 67115.65,
 67076.4,
 67044.24,
 67003.84,
 66927.87,
 66866.54,
 66791.94,
 66735.05,
 66670.34,
 66612.48,
 66554.65,
 66543.29,
 66516.53,
 66531.13,
 66548.73,
 66530.73,
 66538.24,
 66550.8,
 66612.23,
 66679.8,
 66730.81,
 66771.73,
 66830.72,
 66869.73,
 66933.98,
 67042.27,
 67160.58,
 67274.57,
 67479.12,
 67699.83,
 67906.45,
 68108.51,
 68433.69,
 68733.86,
 69026.41,
 69336.94,
 69635.8,
 69914.66,
 70185.36,
 70400.75,
 70582.66,
 70738.92,
 70809.63,
 70920.77,
 71021.65,
 71147.31,
 71086.54,
 71008.03,
 70917.82,
 70802.41,
 70700.48,
 70623.32,
 70485.9,
 70380.3,
 70298.12,
 70248.57,
 70188.45,
 70121.59,
 70052.27,
 69956.06,
 69910.33,
 69866.53,
 69871.61,
 69884.9,
 69874.75,
 69887.65,
 69937.75,
 69970.82,
 69971.42,
 69930.11,
 69890.01,
 69889.62,
 69910.79,
 69926.99,
 69920.41,
 69918.59,
 69899.98,
 69870.54,
 69855.03,
 69792.96,
 69734.33,
 69685.03,
 69666.96,
 69657.1,
 69647.05,
 69606.72,
 69536.93,
 69489.18,
 69479.93,
 69488.03,
 69488.57,
 69495.37,
 69530.01,
 69550.53,
 69469.78,
 69344.7,
 69244.19,
 69123.97,
 68994.9,
 68840.84,
 68678.06,
 68552.45,
 68428.07,
 68285.11,
 68165.43,
 68045.06,
 67885.01,
 67781.43,
 67771.12,
 67768.24,
 67712.81,
 67645.96,
 67611.44,
 67596.95,
 67609.47,
 67577.36,
 67531.45,
 67517.42,
 67453.67,
 67454.91,
 67496.66,
 67526.37,
 67599.74,
 67689.9,
 67819.61,
 67958.9,
 68081.76,
 68195.89,
 68279.8,
 68363.9,
 68454.15,
 68548.95,
 68669.0,
 68734.35,
 68762.34,
 68781.34,
 68769.55,
 68762.85,
 68761.37,
 68800.73,
 68817.07,
 68840.52,
 68874.52,
 68909.57,
 68932.21,
 68940.74,
 68962.69,
 68993.32,
 69024.54,
 69055.94,
 69083.45,
 69101.47,
 69115.42,
 69098.85,
 69102.9,
 69087.74,
 69091.14,
 69087.74,
 69102.68,
 69114.75,
 69134.4,
 69130.62,
 69125.71,
 69134.49,
 69134.19,
 69124.5,
 69113.46,
 69122.83,
 69100.44,
 69093.63,
 69072.52,
 69060.1,
 69043.24,
 69015.76,
 68957.04,
 68914.15,
 68872.81,
 68844.15,
 68839.8,
 68848.24,
 68829.47,
 68792.54,
 68769.44,
 68739.77,
 68730.14,
 68717.56,
 68695.54,
 68685.33,
 68679.34,
 68683.73,
 68713.13,
 68761.58,
 68854.42,
 68929.41,
 69023.03,
 69109.85,
 69162.38,
 69252.86,
 69335.83,
 69404.95,
 69465.02,
 69522.14,
 69534.99,
 69539.17,
 69477.1,
 69355.48,
 69189.47,
 69033.15,
 68855.29,
 68724.9,
 68658.92,
 68582.63,
 68481.55,
 68382.77,
 68265.31,
 68164.71,
 68147.56,
 68078.51,
 68059.39,
 68065.26,
 68092.02,
 68117.24,
 68167.77,
 68200.3,
 68204.74,
 68197.88,
 68210.75,
 68244.74,
 68318.85,
 68381.31,
 68396.36,
 68453.51,
 68465.24,
 68464.74,
 68427.7,
 68403.7,
 68358.14,
 68306.9,
 68269.88,
 68208.38,
 68123.31,
 68042.64,
 67955.62,
 67852.0,
 67757.86,
 67684.46,
 67666.86,
 67653.11,
 67635.02,
 67605.96,
 67608.56,
 67612.2,
 67629.21,
 67666.93,
 67720.85,
 67740.57,
 67738.68,
 67759.83,
 67794.05,
 67826.65,
 67834.98,
 67867.36,
 67936.76,
 67992.23,
 68044.42,
 68096.35,
 68181.84,
 68267.35,
 68304.41,
 68350.46,
 68409.91,
 68454.62,
 68497.92,
 68534.91,
 68579.41,
 68608.46,
 68602.16,
 68613.38,
 68607.09,
 68578.23,
 68496.79,
 68409.35,
 68359.14,
 68348.95,
 68344.16,
 68367.64,
 68348.08,
 68279.63,
 68192.17,
 68096.46,
 68011.24,
 67932.55,
 67878.14,
 67837.93,
 67794.35,
 67749.6,
 67720.32,
 67671.91,
 67615.5,
 67550.18,
 67524.25,
 67536.98,
 67570.61,
 67605.85,
 67626.51,
 67647.16,
 67649.0,
 67643.16,
 67649.99,
 67664.87,
 67677.72,
 67688.27,
 67697.65,
 67695.58,
 67700.98,
 67706.03,
 67710.85,
 67718.22,
 67727.36,
 67731.74,
 67736.04,
 67754.73,
 67761.48,
 67762.58,
 67767.55,
 67771.07,
 67773.72,
 67783.79,
 67778.79,
 67778.79,
 67762.81,
 67743.77,
 67778.88,
 67790.99,
 67819.5,
 67845.46,
 67873.12,
 67899.57,
 67905.99,
 67894.88,
 67895.49,
 67894.79,
 67901.58,
 67914.25,
 67931.08,
 67952.08,
 67968.11,
 68002.48,
 68017.97,
 68036.36,
 68076.2,
 68143.01,
 68216.4,
 68319.64,
 68410.92,
 68487.84,
 68578.11,
 68707.99,
 68852.97,
 68920.97,
 69002.34,
 69049.77,
 69113.07,
 69168.67,
 69204.67,
 69209.12,
 69221.58,
 69214.43,
 69199.79,
 69206.47,
 69216.14,
 69172.81,
 69128.15,
 69148.53,
 69101.43,
 69088.96,
 69070.73,
 69038.45,
 69003.73,
 68988.68,
 68979.73,
 68972.88,
 69024.17,
 69070.61,
 69158.43,
 69277.04,
 69376.59,
 69493.2,
 69598.02,
 69704.97,
 69819.71,
 69942.91,
 70072.9,
 70207.57,
 70352.6,
 70487.7,
 70589.1,
 70697.46,
 70737.1,
 70759.89,
 70805.32,
 70822.03,
 70855.64,
 70884.05,
 70909.17,
 70936.22,
 70949.99,
 70956.57,
 70998.97,
 71032.89,
 71081.56,
 71076.44,
 71096.43,
 71101.93,
 71097.53,
 71113.05,
 71128.32,
 71143.88,
 71154.75,
 71170.47,
 71193.28,
 71206.6,
 71157.7,
 71127.36,
 71083.97,
 71070.2,
 71048.69,
 71033.83,
 71036.09,
 71039.11,
 71040.19,
 71072.08,
 71084.65,
 71069.58,
 71073.03,
 71074.49,
 71044.78,
 71032.78,
 71012.71,
 71012.5,
 70999.66,
 70992.16,
 70968.59,
 70942.65,
 70933.12,
 70916.12,
 70915.45,
 70938.07,
 70938.91,
 70941.92,
 71000.68,
 71047.63,
 71116.17,
 71139.96,
 71192.5,
 71231.63,
 71251.03,
 71254.56,
 71169.84,
 71021.83,
 70876.43,
 70736.59,
 70603.74,
 70488.15,
 70349.12,
 70207.98,
 70048.36,
 69918.93,
 69768.74,
 69617.73,
 69489.76,
 69379.76,
 69363.95,
 69384.09,
 69397.54,
 69407.92,
 69416.2,
 69406.29,
 69411.6,
 69415.9,
 69413.38,
 69410.89,
 69411.46,
 69421.33,
 69431.33,
 69434.13,
 69421.47,
 69414.45,
 69404.97,
 69391.77,
 69385.99,
 69372.76,
 69360.57,
 69349.34,
 69339.59,
 69339.86,
 69329.55,
 69322.21,
 69315.78,
 69313.91,
 69311.25,
 69338.02,
 69349.2,
 69365.02,
 69380.99,
 69412.99,
 69441.64,
 69472.62,
 69502.39,
 69523.52,
 69555.97,
 69576.13,
 69596.0,
 69611.25,
 69629.66,
 69629.88,
 69640.32,
 69653.48,
 69658.61,
 69644.83,
 69619.36,
 69594.32,
 69575.73,
 69558.09,
 69538.37,
 69519.06,
 69501.93,
 69509.22,
 69540.69,
 69558.99,
 69589.69,
 69602.95,
 69596.54,
 69611.02,
 69631.12,
 69638.87,
 69645.3,
 69643.22,
 69589.66,
 69511.42,
 69443.98,
 69326.97,
 69172.5,
 69009.63,
 68833.0,
 68665.63,
 68493.74,
 68302.99,
 68110.45,
 67933.6,
 67738.74,
 67555.91,
 67378.8,
 67251.58,
 67130.65,
 67065.88,
 67030.41,
 67001.7,
 66989.3,
 66978.12,
 66994.55,
 67011.55,
 67032.26,
 67060.49,
 67102.99,
 67148.02,
 67219.35,
 67276.08,
 67324.84,
 67344.57,
 67369.3,
 67419.44,
 67446.71,
 67588.07,
 67731.34,
 67928.53,
 68110.96,
 68268.15,
 68439.08,
 68535.25,
 68555.95,
 68614.68,
 68692.0,
 68760.02,
 68796.5,
 68820.64,
 68835.01,
 68720.41,
 68588.62,
 68400.58,
 68248.44,
 68098.62,
 67950.4,
 67860.22,
 67852.15,
 67831.89,
 67775.03,
 67732.44,
 67684.3,
 67615.41,
 67507.58,
 67453.38,
 67413.74,
 67380.53,
 67309.1,
 67251.55,
 67197.64,
 67149.81,
 67103.61,
 67025.56,
 66958.86,
 66901.89,
 66841.46,
 66795.16,
 66836.77,
 66835.8,
 66834.73,
 66855.37,
 66877.94,
 66889.38,
 66894.1,
 66907.48,
 66928.73,
 66946.96,
 66917.37,
 66798.9,
 66704.05,
 66618.87,
 66509.4,
 66423.98,
 66373.33,
 66292.05,
 66229.47,
 66180.37,
 66111.79,
 66049.8,
 65992.47,
 65939.89,
 65928.44,
 65990.96,
 66038.17,
 66087.92,
 66138.42,
 66176.53,
 66185.38,
 66209.24,
 66228.49,
 66230.98,
 66248.12,
 66245.88,
 66244.61,
 66237.35,
 66231.84,
 66223.23,
 66226.79,
 66225.27,
 66225.36,
 66215.5,
 66205.19,
 66190.54,
 66178.58,
 66174.69,
 66170.97,
 66180.11,
 66181.28,
 66190.37,
 66208.6,
 66256.34,
 66282.48,
 66310.87,
 66349.03,
 66374.53,
 66412.9,
 66444.99,
 66475.85,
 66506.14,
 66527.46,
 66542.14,
 66560.62,
 66595.15,
 66614.22,
 66604.77,
 66603.3,
 66585.19,
 66546.59,
 66541.51,
 66515.71,
 66482.86,
 66453.86,
 66425.61,
 66365.58,
 66320.76,
 66270.2,
 66189.41,
 66083.93,
 66004.57,
 65925.69,
 65893.83,
 65921.35,
 65968.04,
 65992.35,
 66011.32,
 66039.89,
 66072.85,
 66128.73,
 66118.73,
 66069.93,
 66058.67,
 66080.1,
 66087.33,
 66103.62,
 66075.19,
 66008.42,
 65910.28,
 65822.99,
 65754.25,
 65668.1,
 65566.38,
 65447.79,
 65368.08,
 65337.5,
 65282.76,
 65219.19,
 65155.17,
 65070.61,
 65030.37,
 64998.04,
 64966.08,
 64945.03,
 64924.11,
 64900.51,
 64907.36,
 64947.36,
 65003.9,
 65054.41,
 65118.62,
 65169.83,
 65205.97,
 65269.86,
 65311.53,
 65310.82,
 65304.55,
 65298.47,
 65284.86,
 65276.75,
 65247.77,
 65224.91,
 65192.59,
 65154.65,
 65102.85,
 65079.81,
 65054.97,
 65031.23,
 65001.09,
 64997.41,
 64997.79,
 65004.92,
 65030.2,
 65072.48,
 65111.26,
 65166.61,
 65217.87,
 65277.73,
 65373.06,
 65456.31,
 65538.02,
 65550.04,
 65539.62,
 65516.24,
 ...]

In [11]:
#data   : list price
#period : range bollinger
#--return list
Get_bollinger(data=df['close'],period=20)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1043.15,
 1112.04,
 1150.13,
 1167.44,
 1177.44,
 1177.6,
 1171.95,
 1132.63,
 1091.68,
 1037.45,
 954.03,
 859.29,
 694.53,
 517.61,
 169.85,
 160.45,
 159.8,
 146.39,
 120.74,
 119.24,
 142.2,
 144.64,
 148.6,
 165.44,
 171.82,
 169.72,
 169.25,
 169.1,
 164.37,
 159.27,
 160.25,
 160.3,
 159.45,
 158.87,
 159.6,
 151.15,
 139.99,
 125.0,
 124.84,
 123.63,
 121.89,
 118.63,
 123.82,
 120.37,
 148.29,
 164.32,
 204.98,
 210.82,
 210.49,
 209.77,
 199.81,
 194.68,
 195.7,
 204.62,
 203.59,
 196.91,
 169.61,
 175.4,
 189.19,
 194.74,
 302.56,
 435.78,
 565.03,
 614.59,
 663.99,
 710.03,
 746.81,
 769.41,
 802.11,
 832.13,
 827.25,
 818.69,
 829.64,
 829.02,
 807.39,
 741.94,
 676.55,
 559.63,
 358.53,
 207.76,
 190.53,
 200.7,
 194.28,
 258.43,
 307.35,
 363.83,
 414.42,
 462.12,
 483.99,
 504.69,
 524.28,
 531.86,
 508.5,
 504.61,
 512.42,
 510.04,
 473.72,
 437.45,
 404.48,
 373.8,
 343.95,
 301.26,
 192.1,
 174.02,
 165.33,
 168.01,
 175.84,
 187.41,
 218.64,
 236.99,
 313.17,
 371.79,
 398.48,
 570.0,
 727.59,
 882.75,
 1023.4,
 1128.3,
 1233.52,
 1373.18,
 1492.06,
 1554.22,
 1592.85,
 1625.77,
 1646.31,
 1626.49,
 1574.73,
 1492.19,
 1402.37,
 1265.32,
 1145.11,
 993.38,
 742.84,
 634.69,
 546.03,
 465.05,
 406.5,
 298.55,
 208.4,
 219.97,
 225.94,
 300.49,
 375.26,
 417.09,
 440.72,
 456.03,
 460.99,
 467.49,
 479.43,
 481.54,
 488.44,
 488.95,
 476.07,
 451.36,
 414.76,
 400.76,
 386.76,
 396.36,
 398.06,
 451.0,
 469.7,
 485.65,
 460.95,
 497.04,
 562.71,
 585.28,
 591.54,
 595.1,
 590.17,
 583.63,
 549.83,
 506.19,
 481.47,
 419.99,
 375.01,
 342.98,
 340.14,
 314.46,
 300.22,
 294.61,
 261.64,
 242.41,
 119.88,
 134.16,
 133.73,
 133.71,
 122.92,
 124.63,
 125.37,
 125.41,
 123.02,
 121.34,
 119.93,
 119.6,
 119.54,
 119.36,
 119.44,
 119.03,
 117.54,
 132.1,
 139.44,
 144.85,
 143.48,
 131.75,
 146.44,
 152.29,
 155.83,
 159.5,
 166.62,
 169.8,
 164.62,
 156.27,
 157.47,
 179.83,
 191.45,
 215.25,
 307.49,
 356.75,
 385.72,
 396.49,
 410.1,
 409.47,
 406.35,
 401.6,
 376.95,
 375.23,
 372.42,
 352.14,
 317.7,
 315.71,
 306.52,
 318.62,
 323.93,
 330.92,
 345.86,
 353.39,
 354.37,
 452.08,
 538.47,
 648.78,
 894.06,
 1001.86,
 1101.37,
 1166.66,
 1404.69,
 1575.41,
 1683.17,
 1736.69,
 1780.88,
 1768.26,
 1755.59,
 1730.51,
 1655.2,
 1546.56,
 1421.24,
 1241.81,
 1060.15,
 935.57,
 769.27,
 626.37,
 638.83,
 622.06,
 610.17,
 587.35,
 657.22,
 674.18,
 692.27,
 673.27,
 650.66,
 644.4,
 616.96,
 586.58,
 573.62,
 567.34,
 536.3,
 491.19,
 426.38,
 281.88,
 233.95,
 232.32,
 234.48,
 235.72,
 244.88,
 250.63,
 239.93,
 242.47,
 237.23,
 245.72,
 249.7,
 266.14,
 271.03,
 310.95,
 339.78,
 343.09,
 346.97,
 349.75,
 355.24,
 349.68,
 345.19,
 322.48,
 322.44,
 322.69,
 322.51,
 302.63,
 245.95,
 195.08,
 378.69,
 535.28,
 602.42,
 683.24,
 762.6,
 853.44,
 944.26,
 965.68,
 970.77,
 982.71,
 976.97,
 963.64,
 950.26,
 916.1,
 860.3,
 798.49,
 738.35,
 691.74,
 510.26,
 345.05,
 338.07,
 341.72,
 326.83,
 321.41,
 337.2,
 344.52,
 376.02,
 414.15,
 499.83,
 577.66,
 653.53,
 693.74,
 730.13,
 756.48,
 768.33,
 775.19,
 766.76,
 728.77,
 697.67,
 658.99,
 622.97,
 573.2,
 511.12,
 451.4,
 285.27,
 248.76,
 233.02,
 217.79,
 220.52,
 222.05,
 215.07,
 215.61,
 220.11,
 231.33,
 222.85,
 205.06,
 192.01,
 190.49,
 192.3,
 185.64,
 170.56,
 147.17,
 125.93,
 118.76,
 119.1,
 98.22,
 113.38,
 114.16,
 112.86,
 114.09,
 105.6,
 100.96,
 99.9,
 104.38,
 122.24,
 140.62,
 158.04,
 170.04,
 165.58,
 179.06,
 209.26,
 230.36,
 251.95,
 253.52,
 251.27,
 251.47,
 233.46,
 228.33,
 238.24,
 245.63,
 237.79,
 236.63,
 225.03,
 190.53,
 198.5,
 197.62,
 203.27,
 270.57,
 455.45,
 545.82,
 610.88,
 643.61,
 633.08,
 643.27,
 661.37,
 668.54,
 667.03,
 660.07,
 655.29,
 638.77,
 680.9,
 741.54,
 773.58,
 808.34,
 857.05,
 876.23,
 890.87,
 889.03,
 835.45,
 792.03,
 750.3,
 698.28,
 680.19,
 648.14,
 576.12,
 500.95,
 418.41,
 315.02,
 301.48,
 295.56,
 301.04,
 299.25,
 309.87,
 322.44,
 321.14,
 341.5,
 346.18,
 343.65,
 354.36,
 367.53,
 360.05,
 359.05,
 378.52,
 366.07,
 359.62,
 378.03,
 426.07,
 450.76,
 465.48,
 480.97,
 508.26,
 509.8,
 493.7,
 463.82,
 409.39,
 335.08,
 274.49,
 210.89,
 224.59,
 244.45,
 258.49,
 252.52,
 254.21,
 250.56,
 247.39,
 252.75,
 240.98,
 252.66,
 314.38,
 320.38,
 321.25,
 344.75,
 448.03,
 523.0,
 520.71,
 502.96,
 493.04,
 487.02,
 485.38,
 485.32,
 483.95,
 470.81,
 433.71,
 398.43,
 361.4,
 341.82,
 311.56,
 311.38,
 336.14,
 336.75,
 338.17,
 337.28,
 286.46,
 266.99,
 354.44,
 421.53,
 458.41,
 483.81,
 488.29,
 484.9,
 484.86,
 476.92,
 461.94,
 438.92,
 418.59,
 403.12,
 391.42,
 380.35,
 376.47,
 346.29,
 307.54,
 198.08,
 164.51,
 164.08,
 140.81,
 106.76,
 85.13,
 73.26,
 73.41,
 73.16,
 74.36,
 64.86,
 56.18,
 59.23,
 49.35,
 50.51,
 51.68,
 62.98,
 62.3,
 61.56,
 57.46,
 61.48,
 60.83,
 56.27,
 51.91,
 50.8,
 73.11,
 88.26,
 142.57,
 145.9,
 169.03,
 195.92,
 207.06,
 214.32,
 212.95,
 215.24,
 216.06,
 216.1,
 214.94,
 213.09,
 213.66,
 213.9,
 249.87,
 273.61,
 285.78,
 304.81,
 320.0,
 361.82,
 399.86,
 449.71,
 481.7,
 501.74,
 528.25,
 608.27,
 663.67,
 635.15,
 641.25,
 614.1,
 583.46,
 552.63,
 488.97,
 410.0,
 389.35,
 359.49,
 326.83,
 296.8,
 279.36,
 278.04,
 271.53,
 272.63,
 274.71,
 274.83,
 276.34,
 248.89,
 207.81,
 200.9,
 155.73,
 156.65,
 185.47,
 224.41,
 382.08,
 535.07,
 613.49,
 686.27,
 711.94,
 734.5,
 770.52,
 792.43,
 807.07,
 823.69,
 837.72,
 826.79,
 817.23,
 792.54,
 725.97,
 660.37,
 579.1,
 441.62,
 354.43,
 247.89,
 237.61,
 239.3,
 232.78,
 230.78,
 264.51,
 253.69,
 285.28,
 267.56,
 248.5,
 241.48,
 240.96,
 234.28,
 231.62,
 231.9,
 230.81,
 231.13,
 230.35,
 227.12,
 227.06,
 221.65,
 220.3,
 221.92,
 205.96,
 199.81,
 169.82,
 164.07,
 107.86,
 138.52,
 140.0,
 141.57,
 141.04,
 140.24,
 193.46,
 206.78,
 215.36,
 213.8,
 217.99,
 218.57,
 220.02,
 221.81,
 221.56,
 228.08,
 237.95,
 245.06,
 243.44,
 241.3,
 248.92,
 241.35,
 279.77,
 282.44,
 302.6,
 313.16,
 278.46,
 268.81,
 392.84,
 583.0,
 700.49,
 787.54,
 863.83,
 908.17,
 952.37,
 977.3,
 986.61,
 990.29,
 992.28,
 991.27,
 970.08,
 931.12,
 838.66,
 777.06,
 657.87,
 509.53,
 356.43,
 136.19,
 97.83,
 83.79,
 77.34,
 74.16,
 64.49,
 62.25,
 61.41,
 62.2,
 61.26,
 63.6,
 67.21,
 71.27,
 73.79,
 88.47,
 81.3,
 81.56,
 81.39,
 78.89,
 80.15,
 80.15,
 78.32,
 74.0,
 71.6,
 109.17,
 110.37,
 112.21,
 114.91,
 128.52,
 143.19,
 162.1,
 173.32,
 177.87,
 185.15,
 174.12,
 167.64,
 160.12,
 151.24,
 151.06,
 137.55,
 128.12,
 116.8,
 108.23,
 116.36,
 123.27,
 124.22,
 126.81,
 128.17,
 136.95,
 139.99,
 135.86,
 174.85,
 195.04,
 217.55,
 225.01,
 226.49,
 226.3,
 226.33,
 226.13,
 226.44,
 229.11,
 298.52,
 411.87,
 469.45,
 566.07,
 653.29,
 743.12,
 824.24,
 894.64,
 987.21,
 1059.53,
 1091.83,
 1097.03,
 1089.35,
 1069.77,
 1100.96,
 1077.55,
 1018.0,
 930.69,
 806.74,
 663.66,
 580.74,
 533.68,
 450.73,
 405.46,
 364.36,
 345.81,
 335.78,
 333.49,
 335.37,
 336.44,
 340.75,
 344.23,
 358.86,
 389.45,
 324.7,
 507.25,
 626.31,
 806.32,
 915.03,
 983.4,
 1052.64,
 1049.42,
 1041.09,
 1015.36,
 986.36,
 964.2,
 939.04,
 914.79,
 878.6,
 851.85,
 850.5,
 855.06,
 862.43,
 882.79,
 885.03,
 880.48,
 874.52,
 782.92,
 694.29,
 592.6,
 411.91,
 357.1,
 460.84,
 481.64,
 465.2,
 457.52,
 466.3,
 443.29,
 425.93,
 422.94,
 433.64,
 447.11,
 444.8,
 438.81,
 423.66,
 415.21,
 405.57,
 359.49,
 311.87,
 253.11,
 195.99,
 158.36,
 135.88,
 141.93,
 147.84,
 149.07,
 176.09,
 397.1,
 503.15,
 569.49,
 623.81,
 650.45,
 652.52,
 654.15,
 658.06,
 657.26,
 643.9,
 629.27,
 614.77,
 581.26,
 559.88,
 538.49,
 500.21,
 449.05,
 388.14,
 327.33,
 323.38,
 282.87,
 242.2,
 199.44,
 137.26,
 95.06,
 95.45,
 85.12,
 76.36,
 85.59,
 81.87,
 81.98,
 81.19,
 81.73,
 81.99,
 82.85,
 78.43,
 79.04,
 79.91,
 80.66,
 77.69,
 72.2,
 82.36,
 140.16,
 150.76,
 169.42,
 202.7,
 205.9,
 221.26,
 217.4,
 214.97,
 214.91,
 213.41,
 205.26,
 196.26,
 192.41,
 178.9,
 159.4,
 147.06,
 144.53,
 149.33,
 137.12,
 140.92,
 163.55,
 181.31,
 192.62,
 246.8,
 273.93,
 293.02,
 329.74,
 405.78,
 431.17,
 457.92,
 450.84,
 455.34,
 487.07,
 488.0,
 480.32,
 484.82,
 497.55,
 504.34,
 506.14,
 546.68,
 561.14,
 571.09,
 575.57,
 578.85,
 587.17,
 589.42,
 587.21,
 572.72,
 574.37,
 574.47,
 595.41,
 615.05,
 589.22,
 578.05,
 577.29,
 552.06,
 489.61,
 440.99,
 424.87,
 425.03,
 420.02,
 412.18,
 399.27,
 383.22,
 375.35,
 357.43,
 333.64,
 330.12,
 342.09,
 340.34,
 339.19,
 339.97,
 337.07,
 323.01,
 305.65,
 276.84,
 255.95,
 189.25,
 190.45,
 193.32,
 200.83,
 213.81,
 225.39,
 226.56,
 236.24,
 232.01,
 221.73,
 210.96,
 177.92,
 170.62,
 176.67,
 195.45,
 189.48,
 254.93,
 284.52,
 311.19,
 381.53,
 425.59,
 440.78,
 439.04,
 440.05,
 443.09,
 ...]

In [12]:
#data close price
# period range band
#trend = "UP","DOWN"
Get_boll_upband(data=df['close'],period=12,trend="UP")

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 63302.95,
 63300.15,
 63298.69,
 64036.55,
 64319.53,
 64407.68,
 64579.24,
 64494.22,
 64351.54,
 64166.05,
 63860.77,
 63505.74,
 62928.4,
 62307.93,
 61185.58,
 61139.37,
 61109.76,
 61023.8,
 60993.64,
 61032.48,
 61084.39,
 61029.93,
 61029.53,
 61032.27,
 61044.66,
 61049.81,
 61071.27,
 61064.15,
 61162.11,
 61245.09,
 61277.33,
 61337.1,
 61362.44,
 61368.36,
 61368.72,
 61357.95,
 61334.16,
 61302.33,
 61306.98,
 61298.95,
 61265.78,
 61235.15,
 61224.9,
 61155.84,
 61110.84,
 61120.01,
 61128.75,
 61183.98,
 61211.27,
 61243.92,
 61272.49,
 61292.18,
 61396.41,
 61449.33,
 61598.8,
 61624.95,
 61610.65,
 61606.63,
 61581.1,
 61583.01,
 61609.0,
 61631.8,
 61628.42,
 61663.66,
 61663.09,
 61700.01,
 61672.48,
 61702.94,
 62100.1,
 62581.0,
 63048.25,
 63267.62,
 63465.88,
 63659.43,
 63799.5,
 63854.52,
 63926.45,
 63907.46,
 63569.51,
 63234.13,
 63231.79,
 63270.67,
 63244.4,
 63234.52,
 63235.18,
 63235.68,
 63252.28,
 63285.91,
 63296.85,
 63221.08,
 63215.35,
 63330.99,
 63283.52,
 63246.76,
 63224.13,
 63204.27,
 63074.46,
 62975.24,
 62867.23,
 62758.75,
 62643.71,
 62496.61,
 62171.06,
 62107.56,
 62010.68,
 61964.59,
 61942.1,
 61940.17,
 61901.63,
 61905.11,
 61905.11,
 61895.69,
 61957.96,
 62017.27,
 62040.96,
 62075.29,
 62202.65,
 62277.76,
 62550.26,
 62751.68,
 62823.44,
 63403.32,
 63982.33,
 64539.54,
 65041.38,
 65417.19,
 65774.61,
 66236.15,
 66667.39,
 66891.94,
 67044.18,
 67124.72,
 66920.87,
 66896.87,
 66836.77,
 66763.85,
 66682.82,
 66481.25,
 66236.66,
 66217.07,
 66247.64,
 66331.76,
 66416.92,
 66426.09,
 66526.73,
 66522.53,
 66569.24,
 66619.26,
 66624.35,
 66770.69,
 66901.71,
 66943.27,
 66917.9,
 66821.91,
 66673.28,
 66559.34,
 66273.8,
 66157.48,
 65804.34,
 65759.27,
 65655.78,
 65675.96,
 65725.39,
 65886.06,
 66210.96,
 66337.3,
 66510.64,
 66697.34,
 66734.82,
 66818.85,
 66780.79,
 66923.48,
 67194.78,
 67244.9,
 67232.52,
 67260.06,
 67365.71,
 67392.39,
 67410.36,
 67424.37,
 67439.42,
 67434.7,
 67182.13,
 67183.4,
 67098.9,
 67093.78,
 67071.64,
 67072.15,
 67033.75,
 67064.36,
 67121.36,
 67193.71,
 67240.29,
 67239.37,
 67240.44,
 67250.34,
 67252.98,
 67252.92,
 67252.41,
 67257.18,
 67257.68,
 67249.02,
 67209.77,
 67117.28,
 66996.47,
 66986.78,
 66993.27,
 67125.26,
 67189.6,
 67234.51,
 67254.37,
 67243.69,
 67331.1,
 67350.12,
 67362.29,
 67392.32,
 67423.92,
 67442.83,
 67427.69,
 67428.43,
 67432.43,
 67475.92,
 67487.89,
 67518.86,
 67608.31,
 67612.16,
 67551.78,
 67424.29,
 67233.49,
 67182.49,
 67051.44,
 66974.61,
 66904.2,
 67082.94,
 67216.78,
 67203.92,
 67220.94,
 67222.34,
 67248.79,
 67324.32,
 67320.22,
 67317.92,
 67342.22,
 67353.3,
 67474.13,
 67925.1,
 68295.0,
 68698.22,
 69603.87,
 70021.12,
 70410.59,
 70678.93,
 71509.22,
 72025.36,
 72309.1,
 72449.52,
 72485.72,
 72455.08,
 72377.61,
 72243.92,
 72251.04,
 72124.96,
 71975.97,
 71502.18,
 71418.63,
 71431.43,
 71505.92,
 71615.3,
 71745.33,
 71873.85,
 71830.71,
 71743.38,
 71778.62,
 71686.44,
 71542.03,
 71359.13,
 71103.77,
 70618.49,
 70465.13,
 70417.37,
 70428.5,
 70434.47,
 70437.61,
 70438.86,
 70341.79,
 70347.41,
 70343.33,
 70333.15,
 70303.2,
 70279.2,
 70230.96,
 70261.5,
 70430.52,
 70478.39,
 70477.17,
 70495.16,
 70500.76,
 70510.76,
 70499.62,
 70478.38,
 70503.06,
 70498.72,
 70496.75,
 70401.68,
 70117.78,
 69866.58,
 69751.15,
 69748.17,
 69782.34,
 69828.33,
 69853.55,
 69811.54,
 69895.65,
 69900.27,
 70417.63,
 70692.25,
 70749.45,
 70777.82,
 70783.19,
 70740.7,
 70599.29,
 70338.39,
 70033.18,
 69696.13,
 68994.84,
 68292.64,
 68240.25,
 68277.6,
 68231.57,
 68220.08,
 68252.99,
 68372.6,
 68379.93,
 68371.73,
 68291.05,
 68267.85,
 68167.98,
 68097.47,
 68047.5,
 68005.23,
 68200.87,
 68431.08,
 68866.28,
 69170.16,
 69464.1,
 69598.29,
 69713.63,
 69760.4,
 69720.58,
 69661.5,
 69337.33,
 69213.41,
 69178.16,
 69139.0,
 69115.75,
 69073.25,
 68948.12,
 68959.73,
 69051.78,
 69277.52,
 69327.37,
 69357.13,
 69362.31,
 69376.96,
 69375.92,
 69374.91,
 69374.2,
 69372.25,
 69354.54,
 69342.65,
 69347.53,
 69249.81,
 69304.76,
 69310.85,
 69320.1,
 69336.97,
 69325.39,
 69318.38,
 69322.71,
 69305.02,
 69360.95,
 69366.11,
 69363.04,
 69377.33,
 69343.76,
 69340.65,
 69336.88,
 69352.35,
 69390.19,
 69421.62,
 69442.02,
 69448.35,
 69374.2,
 69360.92,
 69387.5,
 69337.6,
 69298.27,
 69271.66,
 69251.64,
 69175.25,
 69179.07,
 69175.81,
 69183.17,
 69199.95,
 69167.49,
 69161.98,
 69159.27,
 69158.75,
 69166.43,
 69145.58,
 69092.09,
 69296.95,
 69963.45,
 70312.82,
 70593.01,
 70740.0,
 70747.66,
 70789.78,
 70825.84,
 70793.76,
 70671.96,
 70545.31,
 70630.33,
 70715.63,
 70719.48,
 70718.27,
 70539.23,
 70353.3,
 70338.52,
 70128.28,
 69807.71,
 69531.49,
 69237.63,
 68851.66,
 68771.25,
 68618.28,
 68669.9,
 68681.87,
 68688.64,
 68689.3,
 68730.18,
 68754.14,
 68768.04,
 68776.17,
 68778.06,
 68832.12,
 68882.72,
 68962.93,
 69067.36,
 69094.81,
 69018.59,
 68889.17,
 68999.45,
 69083.02,
 69126.95,
 69110.14,
 69141.26,
 69120.88,
 69072.26,
 68994.88,
 68857.76,
 68606.9,
 68398.08,
 68165.53,
 68163.31,
 68126.41,
 68082.94,
 67999.2,
 67978.65,
 67901.57,
 67869.96,
 67968.22,
 68112.59,
 68244.1,
 68338.03,
 68332.86,
 68276.12,
 68255.68,
 68255.53,
 68271.21,
 68267.32,
 68299.14,
 68537.33,
 68612.6,
 68716.72,
 68851.11,
 69228.8,
 69526.27,
 69535.55,
 69507.73,
 69460.82,
 69430.07,
 69356.64,
 69332.12,
 69325.15,
 69324.3,
 69324.46,
 69313.3,
 69087.4,
 68662.82,
 68637.11,
 68654.46,
 68711.68,
 68712.83,
 68712.61,
 68762.39,
 68759.81,
 68865.35,
 68963.25,
 68972.86,
 68916.92,
 68862.45,
 68805.58,
 68750.94,
 68720.51,
 68586.88,
 68417.66,
 68012.98,
 67828.16,
 67874.14,
 67881.43,
 67842.05,
 67819.76,
 67798.34,
 67792.54,
 67791.32,
 67799.96,
 67782.04,
 67765.44,
 67773.74,
 67757.01,
 67788.06,
 67785.24,
 67786.57,
 67810.33,
 67818.15,
 67819.49,
 67836.03,
 67841.27,
 67832.51,
 67825.71,
 67871.06,
 67870.34,
 67863.84,
 67862.2,
 67874.34,
 67874.32,
 67886.45,
 67889.16,
 67886.54,
 67940.11,
 67964.09,
 68151.8,
 68161.41,
 68254.06,
 68358.99,
 68410.8,
 68444.92,
 68445.49,
 68448.38,
 68447.71,
 68447.4,
 68416.98,
 68372.37,
 68308.54,
 68305.09,
 68431.21,
 68489.3,
 68555.09,
 68662.79,
 68832.01,
 69077.67,
 69208.96,
 69385.3,
 69465.66,
 69496.97,
 69480.48,
 69645.14,
 69879.95,
 69852.12,
 69926.79,
 69886.17,
 69878.2,
 69893.03,
 69889.07,
 69888.39,
 69886.65,
 69876.46,
 69899.85,
 69764.27,
 69570.86,
 69543.97,
 69379.18,
 69378.82,
 69348.3,
 69303.34,
 69270.16,
 69272.68,
 69292.15,
 69282.45,
 69276.79,
 69273.08,
 69420.83,
 69604.35,
 70136.15,
 70659.98,
 70952.48,
 71220.12,
 71360.36,
 71438.43,
 71487.4,
 71482.6,
 71405.81,
 71232.21,
 71194.75,
 71004.16,
 71064.51,
 71185.42,
 71239.39,
 71317.64,
 71381.12,
 71346.62,
 71336.71,
 71303.65,
 71243.86,
 71230.61,
 71248.77,
 71247.07,
 71470.47,
 71507.01,
 71670.63,
 71668.4,
 71682.78,
 71699.35,
 71704.14,
 71694.47,
 71694.35,
 71690.33,
 71643.61,
 71614.38,
 71513.12,
 71489.77,
 71298.19,
 71318.29,
 71264.53,
 71242.53,
 71222.44,
 71195.93,
 71215.61,
 71251.98,
 71251.77,
 71385.33,
 71434.1,
 71433.41,
 71432.69,
 71424.56,
 71542.45,
 71559.34,
 71568.09,
 71565.28,
 71538.63,
 71500.85,
 71471.08,
 71303.56,
 71196.16,
 71279.09,
 71345.56,
 71400.73,
 71379.57,
 71389.77,
 71436.01,
 71507.11,
 71671.12,
 71670.36,
 71711.42,
 71686.67,
 71666.85,
 71716.07,
 72111.89,
 72472.91,
 72613.91,
 72650.6,
 72594.11,
 72433.1,
 72120.35,
 71883.54,
 71459.63,
 70950.45,
 70432.03,
 69717.84,
 69549.3,
 69523.98,
 69579.63,
 69584.41,
 69574.67,
 69564.33,
 69563.85,
 69563.57,
 69557.39,
 69563.77,
 69563.51,
 69558.57,
 69554.97,
 69551.3,
 69498.47,
 69499.28,
 69495.35,
 69494.91,
 69505.02,
 69522.6,
 69523.65,
 69535.72,
 69524.58,
 69517.21,
 69494.7,
 69475.11,
 69434.6,
 69429.58,
 69417.85,
 69419.54,
 69430.03,
 69605.65,
 69626.46,
 69633.97,
 69649.56,
 69695.52,
 69739.52,
 69804.99,
 69835.3,
 69853.77,
 69879.5,
 69860.78,
 69830.66,
 69815.91,
 69802.32,
 69798.52,
 69778.15,
 69779.58,
 69783.91,
 69807.47,
 69851.87,
 69848.72,
 69809.07,
 69794.69,
 69772.09,
 69769.88,
 69745.41,
 69724.93,
 69932.8,
 70027.94,
 70146.12,
 70193.97,
 70181.71,
 70179.67,
 70177.34,
 70173.93,
 70171.4,
 70165.16,
 70349.11,
 70572.64,
 70531.23,
 70537.05,
 70443.6,
 70353.4,
 70302.08,
 70139.95,
 69974.2,
 69748.19,
 69388.02,
 68910.72,
 68650.93,
 68485.6,
 68264.72,
 68078.93,
 67851.95,
 67690.42,
 67631.62,
 67553.53,
 67633.19,
 67708.22,
 67767.01,
 67790.27,
 67813.9,
 67876.38,
 67772.73,
 67666.56,
 67543.07,
 67520.7,
 67533.09,
 67542.1,
 67682.45,
 67897.72,
 67971.18,
 68813.51,
 69296.39,
 69926.44,
 70307.71,
 70570.52,
 70787.71,
 70747.11,
 70735.52,
 70654.85,
 70608.33,
 70583.08,
 70525.04,
 70457.53,
 70393.64,
 70112.74,
 69852.94,
 69551.74,
 68949.94,
 68720.98,
 68713.35,
 68681.78,
 68506.25,
 68370.31,
 68232.32,
 68010.41,
 67909.72,
 67896.25,
 68207.59,
 68234.11,
 68230.51,
 68228.2,
 68197.26,
 68152.93,
 68110.74,
 67942.69,
 67765.83,
 67526.03,
 67287.06,
 67119.83,
 67066.74,
 67033.55,
 67078.91,
 67099.43,
 67088.2,
 67163.82,
 67155.74,
 67153.79,
 67179.71,
 67203.0,
 67222.77,
 67225.79,
 67338.48,
 67841.15,
 67965.08,
 67987.4,
 67968.49,
 67827.02,
 67719.57,
 67600.77,
 67414.46,
 67190.34,
 66908.74,
 66620.23,
 66581.75,
 66585.2,
 66569.25,
 66526.75,
 66405.42,
 66334.55,
 66340.26,
 66352.13,
 66363.71,
 66395.04,
 66393.07,
 66393.16,
 66402.37,
 66401.71,
 66403.07,
 66405.78,
 66387.58,
 66415.99,
 66418.31,
 66404.78,
 66386.24,
 66349.55,
 66319.11,
 66312.5,
 66267.03,
 66264.75,
 66270.5,
 66313.48,
 66331.06,
 66328.03,
 66389.04,
 66593.88,
 66638.35,
 66704.48,
 66813.76,
 66824.55,
 66869.48,
 66867.0,
 66866.17,
 66865.19,
 66839.0,
 66791.04,
 66773.08,
 66787.31,
 66794.11,
 66793.64,
 66760.54,
 66795.51,
 66817.27,
 66806.91,
 66801.84,
 66826.35,
 66824.96,
 66816.78,
 66900.01,
 66816.81,
 66736.35,
 66688.61,
 66743.25,
 66698.27,
 66669.48,
 66536.9,
 66637.9,
 66995.7,
 67121.81,
 67159.18,
 67263.41,
 67369.7,
 67429.91,
 67422.38,
 67436.42,
 67437.1,
 67419.12,
 67433.63,
 67354.92,
 67082.12,
 66902.07,
 66790.84,
 66585.9,
 66260.37,
 65853.83,
 65812.62,
 65912.34,
 66038.94,
 66071.82,
 66055.21,
 66014.36,
 65957.96,
 65850.21,
 65647.02,
 65569.51,
 65516.05,
 65455.32,
 65429.75,
 65454.26,
 65543.78,
 65638.61,
 65714.93,
 65747.42,
 65813.29,
 65641.69,
 65602.67,
 65606.31,
 65650.61,
 65648.46,
 65643.58,
 65630.73,
 65672.18,
 65684.62,
 65670.75,
 65631.95,
 65512.2,
 65482.57,
 65474.47,
 65423.32,
 65242.14,
 65182.16,
 65143.21,
 65169.47,
 65227.74,
 65270.41,
 65343.97,
 65484.38,
 65573.72,
 65795.26,
 65884.17,
 65968.03,
 66178.74,
 66321.03,
 66375.22,
 66377.5,
 66417.73,
 66474.81,
 ...]

In [13]:
#close   : list price
#high : list price
#low   : list price
#volume : list price
#--return list
Get_VWap(close=df["close"],high=df["high"],low=df["low"],volume=df["volume"])

[62892.25,
 62864.91,
 62877.2,
 62877.96,
 62883.85,
 62871.04,
 62901.87,
 62993.04,
 62994.3,
 62999.57,
 63000.13,
 63012.94,
 63027.33,
 63023.91,
 62527.15,
 62261.94,
 62093.27,
 61942.72,
 61879.6,
 61822.74,
 61779.44,
 61760.31,
 61744.93,
 61734.54,
 61715.56,
 61699.01,
 61688.43,
 61680.59,
 61667.69,
 61658.82,
 61649.58,
 61643.0,
 61633.65,
 61611.96,
 61605.71,
 61591.3,
 61582.98,
 61574.75,
 61567.95,
 61554.37,
 61548.32,
 61544.17,
 61541.7,
 61539.45,
 61532.31,
 61529.34,
 61525.99,
 61521.43,
 61516.57,
 61512.92,
 61509.76,
 61506.98,
 61503.79,
 61501.95,
 61500.09,
 61491.36,
 61486.18,
 61482.4,
 61476.46,
 61474.36,
 61472.18,
 61470.73,
 61468.63,
 61467.22,
 61468.94,
 61468.97,
 61468.91,
 61468.06,
 61467.39,
 61463.66,
 61462.74,
 61462.57,
 61463.97,
 61462.8,
 61455.07,
 61442.08,
 61436.73,
 61432.37,
 61430.03,
 61449.82,
 61526.35,
 61560.13,
 61588.0,
 61599.13,
 61625.1,
 61644.54,
 61661.69,
 61680.64,
 61714.78,
 61731.66,
 61739.34,
 61759.37,
 61766.87,
 61772.18,
 61778.82,
 61784.49,
 61795.51,
 61803.42,
 61812.64,
 61821.68,
 61826.54,
 61832.05,
 61839.62,
 61841.38,
 61841.66,
 61841.64,
 61840.52,
 61840.27,
 61834.53,
 61833.4,
 61830.96,
 61831.0,
 61825.65,
 61818.89,
 61816.74,
 61815.54,
 61815.0,
 61814.27,
 61813.72,
 61813.2,
 61811.5,
 61810.75,
 61810.68,
 61811.07,
 61811.39,
 61812.09,
 61812.56,
 61814.77,
 61816.65,
 61825.63,
 61839.76,
 61845.53,
 61916.57,
 61997.2,
 62044.85,
 62111.21,
 62147.65,
 62177.22,
 62238.51,
 62309.06,
 62340.05,
 62358.61,
 62385.52,
 62415.87,
 62456.62,
 62477.8,
 62497.17,
 62512.12,
 62525.21,
 62535.55,
 62554.86,
 62581.28,
 62603.01,
 62623.41,
 62638.4,
 62657.74,
 62705.54,
 62737.37,
 62777.55,
 62806.47,
 62850.41,
 62878.18,
 62896.31,
 62908.86,
 62915.63,
 62922.91,
 62930.0,
 62938.13,
 62945.47,
 62951.63,
 62956.04,
 62976.2,
 62983.22,
 62989.33,
 63006.57,
 63049.46,
 63067.17,
 63078.09,
 63092.24,
 63104.33,
 63122.25,
 63140.7,
 63165.81,
 63233.57,
 63257.5,
 63275.77,
 63297.46,
 63314.63,
 63322.43,
 63327.72,
 63332.82,
 63343.68,
 63360.94,
 63366.96,
 63375.13,
 63382.58,
 63389.26,
 63393.36,
 63401.06,
 63414.61,
 63421.73,
 63431.21,
 63453.39,
 63471.84,
 63481.52,
 63492.07,
 63512.36,
 63522.12,
 63528.59,
 63535.62,
 63538.8,
 63541.94,
 63546.02,
 63549.48,
 63556.6,
 63561.45,
 63564.72,
 63567.36,
 63581.55,
 63590.24,
 63595.07,
 63598.71,
 63603.84,
 63616.07,
 63622.73,
 63629.16,
 63657.52,
 63677.39,
 63693.15,
 63706.09,
 63715.94,
 63724.06,
 63736.58,
 63744.03,
 63748.58,
 63771.96,
 63778.02,
 63782.36,
 63787.45,
 63791.17,
 63797.39,
 63807.44,
 63815.03,
 63820.34,
 63834.83,
 63847.79,
 63860.57,
 63871.98,
 63880.64,
 63887.89,
 63906.89,
 63917.78,
 63928.24,
 63943.53,
 63958.84,
 63984.68,
 64043.49,
 64083.04,
 64110.56,
 64257.72,
 64367.18,
 64421.8,
 64462.29,
 64583.02,
 64679.93,
 64755.69,
 64815.8,
 64855.04,
 64881.51,
 64915.11,
 64946.72,
 64980.21,
 65006.44,
 65031.54,
 65064.52,
 65112.73,
 65157.2,
 65212.88,
 65253.27,
 65290.84,
 65326.21,
 65356.23,
 65367.42,
 65387.16,
 65399.59,
 65407.24,
 65423.87,
 65434.24,
 65447.67,
 65458.21,
 65472.76,
 65481.95,
 65497.42,
 65506.05,
 65514.05,
 65523.22,
 65537.25,
 65543.99,
 65552.89,
 65563.55,
 65579.41,
 65593.8,
 65616.53,
 65634.43,
 65647.68,
 65666.81,
 65692.47,
 65703.38,
 65718.34,
 65732.75,
 65741.45,
 65747.78,
 65755.97,
 65761.71,
 65765.95,
 65771.75,
 65778.14,
 65783.25,
 65789.08,
 65797.37,
 65803.64,
 65811.41,
 65818.32,
 65834.62,
 65856.59,
 65889.9,
 65906.19,
 65916.16,
 65921.15,
 65926.21,
 65936.85,
 65941.92,
 65958.26,
 65980.59,
 65984.47,
 65988.64,
 65993.57,
 65995.99,
 65999.78,
 66003.88,
 66007.83,
 66012.26,
 66017.58,
 66021.07,
 66024.08,
 66026.55,
 66028.38,
 66030.52,
 66032.95,
 66038.83,
 66046.73,
 66056.56,
 66064.71,
 66075.87,
 66087.14,
 66092.75,
 66097.18,
 66099.65,
 66101.54,
 66103.89,
 66105.81,
 66107.83,
 66110.04,
 66113.19,
 66115.86,
 66117.36,
 66119.44,
 66121.31,
 66125.07,
 66128.49,
 66133.78,
 66141.57,
 66147.42,
 66154.45,
 66158.38,
 66162.7,
 66165.64,
 66167.71,
 66170.12,
 66171.8,
 66173.25,
 66174.72,
 66176.22,
 66179.36,
 66181.42,
 66183.0,
 66186.41,
 66189.25,
 66190.87,
 66192.22,
 66193.92,
 66198.02,
 66203.51,
 66206.84,
 66210.02,
 66213.39,
 66216.35,
 66218.63,
 66222.96,
 66229.51,
 66234.06,
 66236.32,
 66238.27,
 66239.59,
 66240.54,
 66244.59,
 66246.39,
 66248.64,
 66251.17,
 66255.48,
 66260.03,
 66266.12,
 66268.61,
 66272.59,
 66275.32,
 66278.52,
 66282.64,
 66285.64,
 66288.45,
 66292.29,
 66295.33,
 66301.13,
 66310.73,
 66339.39,
 66355.14,
 66361.83,
 66367.02,
 66376.26,
 66381.69,
 66384.62,
 66388.1,
 66391.98,
 66396.99,
 66404.95,
 66412.81,
 66421.85,
 66426.24,
 66429.35,
 66432.06,
 66435.59,
 66440.21,
 66444.98,
 66452.96,
 66456.66,
 66460.23,
 66467.75,
 66474.02,
 66478.73,
 66482.57,
 66485.55,
 66489.21,
 66494.97,
 66496.93,
 66498.5,
 66500.91,
 66502.28,
 66504.16,
 66506.72,
 66510.29,
 66513.99,
 66517.41,
 66519.57,
 66521.73,
 66526.31,
 66529.89,
 66532.58,
 66534.28,
 66535.95,
 66539.09,
 66544.93,
 66548.09,
 66551.4,
 66554.04,
 66555.47,
 66556.6,
 66557.58,
 66558.41,
 66559.49,
 66560.3,
 66561.19,
 66562.29,
 66563.55,
 66565.97,
 66567.47,
 66569.89,
 66571.23,
 66575.02,
 66578.06,
 66581.31,
 66582.98,
 66585.08,
 66586.96,
 66591.18,
 66597.19,
 66603.85,
 66608.76,
 66612.14,
 66625.48,
 66631.79,
 66637.91,
 66642.29,
 66643.52,
 66644.65,
 66645.89,
 66647.22,
 66649.14,
 66651.56,
 66652.6,
 66654.59,
 66656.49,
 66658.02,
 66660.57,
 66662.02,
 66664.12,
 66666.35,
 66669.05,
 66677.41,
 66683.25,
 66688.72,
 66690.46,
 66692.28,
 66693.2,
 66694.22,
 66696.86,
 66697.72,
 66698.53,
 66699.06,
 66700.12,
 66700.97,
 66701.77,
 66702.29,
 66702.8,
 66703.31,
 66703.82,
 66704.25,
 66704.78,
 66705.38,
 66705.95,
 66706.44,
 66706.83,
 66707.51,
 66708.23,
 66708.88,
 66709.41,
 66709.89,
 66711.86,
 66712.34,
 66712.62,
 66713.2,
 66713.69,
 66714.14,
 66714.42,
 66714.96,
 66715.67,
 66716.22,
 66716.63,
 66716.95,
 66717.3,
 66717.87,
 66718.44,
 66719.03,
 66720.39,
 66720.86,
 66723.38,
 66725.34,
 66726.87,
 66731.95,
 66733.0,
 66733.95,
 66736.18,
 66738.38,
 66740.49,
 66741.07,
 66741.52,
 66742.13,
 66742.61,
 66743.49,
 66746.81,
 66750.07,
 66751.89,
 66754.05,
 66756.41,
 66764.94,
 66769.77,
 66774.35,
 66776.69,
 66780.11,
 66783.24,
 66791.19,
 66804.12,
 66817.23,
 66824.34,
 66830.19,
 66832.94,
 66835.37,
 66837.72,
 66841.06,
 66842.93,
 66844.77,
 66846.2,
 66848.93,
 66850.61,
 66852.09,
 66853.47,
 66854.78,
 66856.23,
 66859.73,
 66861.52,
 66863.76,
 66867.22,
 66869.14,
 66870.74,
 66873.8,
 66882.54,
 66896.54,
 66912.16,
 66932.01,
 66939.84,
 66954.71,
 66962.25,
 66965.58,
 66968.45,
 66972.4,
 66974.86,
 66980.4,
 66989.12,
 66996.89,
 67001.27,
 67009.17,
 67013.76,
 67020.8,
 67028.5,
 67034.68,
 67038.84,
 67043.43,
 67047.48,
 67055.17,
 67064.1,
 67073.74,
 67090.3,
 67099.52,
 67107.92,
 67118.13,
 67123.4,
 67127.38,
 67129.39,
 67131.52,
 67137.09,
 67139.63,
 67142.3,
 67144.81,
 67147.1,
 67150.25,
 67153.72,
 67156.7,
 67159.86,
 67162.54,
 67165.53,
 67167.75,
 67172.05,
 67179.72,
 67190.27,
 67199.21,
 67207.92,
 67219.37,
 67226.08,
 67229.11,
 67235.67,
 67242.95,
 67244.88,
 67248.03,
 67250.93,
 67252.87,
 67255.21,
 67257.43,
 67259.66,
 67265.08,
 67274.16,
 67277.28,
 67281.69,
 67285.53,
 67288.7,
 67291.8,
 67298.8,
 67328.45,
 67336.78,
 67342.03,
 67350.19,
 67355.48,
 67364.9,
 67383.93,
 67388.35,
 67390.98,
 67392.18,
 67393.7,
 67394.82,
 67396.29,
 67397.65,
 67398.43,
 67399.44,
 67400.5,
 67401.36,
 67402.35,
 67403.79,
 67404.75,
 67405.6,
 67406.6,
 67407.98,
 67409.06,
 67411.02,
 67412.39,
 67413.27,
 67414.69,
 67415.93,
 67416.62,
 67417.27,
 67418.02,
 67418.47,
 67418.96,
 67419.57,
 67420.22,
 67420.71,
 67421.58,
 67422.29,
 67422.79,
 67423.27,
 67423.87,
 67424.75,
 67425.26,
 67425.74,
 67426.31,
 67426.86,
 67429.23,
 67433.16,
 67434.87,
 67436.73,
 67437.77,
 67438.54,
 67440.71,
 67442.32,
 67443.19,
 67443.98,
 67444.77,
 67445.24,
 67446.42,
 67447.7,
 67449.73,
 67450.65,
 67451.43,
 67452.33,
 67454.32,
 67455.93,
 67457.24,
 67459.04,
 67460.11,
 67461.27,
 67462.36,
 67464.34,
 67466.44,
 67472.85,
 67476.35,
 67478.15,
 67481.74,
 67485.2,
 67488.38,
 67489.24,
 67490.15,
 67491.0,
 67492.06,
 67495.7,
 67500.16,
 67501.52,
 67503.53,
 67504.21,
 67504.55,
 67504.78,
 67504.74,
 67504.04,
 67502.84,
 67501.63,
 67500.69,
 67498.84,
 67497.86,
 67493.22,
 67490.81,
 67489.19,
 67488.27,
 67488.05,
 67487.89,
 67487.81,
 67487.77,
 67487.71,
 67487.57,
 67487.17,
 67487.07,
 67487.01,
 67487.01,
 67486.89,
 67486.78,
 67486.71,
 67486.68,
 67486.84,
 67487.44,
 67487.74,
 67496.15,
 67501.93,
 67508.14,
 67512.87,
 67515.94,
 67518.91,
 67526.92,
 67529.46,
 67530.35,
 67531.32,
 67531.88,
 67532.22,
 67532.74,
 67533.13,
 67533.66,
 67533.38,
 67533.3,
 67533.3,
 67533.26,
 67533.32,
 67533.37,
 67533.2,
 67533.37,
 67533.64,
 67534.65,
 67535.19,
 67534.9,
 67532.18,
 67530.2,
 67529.4,
 67528.8,
 67528.06,
 67527.51,
 67527.14,
 67526.86,
 67526.56,
 67525.92,
 67525.33,
 67524.83,
 67524.41,
 67524.11,
 67523.6,
 67523.18,
 67522.61,
 67522.06,
 67521.59,
 67521.19,
 67520.74,
 67520.33,
 67519.81,
 67518.5,
 67516.93,
 67506.15,
 67502.61,
 67498.93,
 67497.04,
 67495.38,
 67492.84,
 67491.53,
 67490.99,
 67489.82,
 67489.28,
 67488.85,
 67488.23,
 67487.58,
 67487.0,
 67485.9,
 67484.36,
 67483.97,
 67483.52,
 67483.06,
 67482.44,
 67482.03,
 67481.61,
 67480.88,
 67479.86,
 67479.33,
 67478.78,
 67478.32,
 67477.97,
 67476.9,
 67476.55,
 67476.07,
 67475.79,
 67475.5,
 67475.15,
 67474.94,
 67474.72,
 67474.44,
 67474.06,
 67473.55,
 67473.22,
 67472.96,
 67471.93,
 67471.19,
 67470.76,
 67470.47,
 67470.02,
 67469.44,
 67469.17,
 67468.86,
 67468.53,
 67468.32,
 67468.15,
 67467.86,
 67467.67,
 67466.84,
 67466.54,
 67465.95,
 67464.94,
 67463.71,
 67463.06,
 67462.5,
 67461.98,
 67460.91,
 67459.54,
 67458.58,
 67456.55,
 67454.21,
 67453.08,
 67451.5,
 67447.87,
 67445.1,
 67442.4,
 67438.77,
 67436.69,
 67435.24,
 67434.55,
 67433.13,
 67432.58,
 67432.22,
 67431.3,
 67428.54,
 67418.19,
 67411.17,
 67408.92,
 67406.92,
 67405.12,
 67402.79,
 67401.22,
 67400.33,
 67399.0,
 67397.29,
 67394.1,
 67390.0,
 67382.63,
 67373.16,
 67366.22,
 67360.8,
 67356.89,
 67353.62,
 67347.42,
 67341.89,
 67339.58,
 67337.99,
 67336.31,
 67334.07,
 67329.5,
 67327.57,
 67325.63,
 67323.6,
 67322.49,
 67321.28,
 67319.26,
 67317.88,
 67316.29,
 67314.99,
 67311.79,
 67310.52,
 67309.32,
 67306.63,
 67304.85,
 67303.07,
 67301.25,
 67300.26,
 67299.24,
 67297.87,
 67297.1,
 67296.42,
 67295.79,
 67293.55,
 67292.15,
 67290.88,
 67290.13,
 67289.21,
 67287.85,
 67286.48,
 67284.88,
 67283.88,
 67282.79,
 67281.79,
 67280.43,
 67278.96,
 67274.41,
 67270.13,
 67267.04,
 ...]

In [14]:
#df 
#--return list
Get_VWap2(df)

[62892.25,
 62864.91,
 62877.2,
 62877.96,
 62883.85,
 62871.04,
 62901.87,
 62993.04,
 62994.3,
 62999.57,
 63000.13,
 63012.94,
 63027.33,
 63023.91,
 62527.15,
 62261.94,
 62093.27,
 61942.72,
 61879.6,
 61822.74,
 61779.44,
 61760.31,
 61744.93,
 61734.54,
 61715.56,
 61699.01,
 61688.43,
 61680.59,
 61667.69,
 61658.82,
 61649.58,
 61643.0,
 61633.65,
 61611.96,
 61605.71,
 61591.3,
 61582.98,
 61574.75,
 61567.95,
 61554.37,
 61548.32,
 61544.17,
 61541.7,
 61539.45,
 61532.31,
 61529.34,
 61525.99,
 61521.43,
 61516.57,
 61512.92,
 61509.76,
 61506.98,
 61503.79,
 61501.95,
 61500.09,
 61491.36,
 61486.18,
 61482.4,
 61476.46,
 61474.36,
 61472.18,
 61470.73,
 61468.63,
 61467.22,
 61468.94,
 61468.97,
 61468.91,
 61468.06,
 61467.39,
 61463.66,
 61462.74,
 61462.57,
 61463.97,
 61462.8,
 61455.07,
 61442.08,
 61436.73,
 61432.37,
 61430.03,
 61449.82,
 61526.35,
 61560.13,
 61588.0,
 61599.13,
 61625.1,
 61644.54,
 61661.69,
 61680.64,
 61714.78,
 61731.66,
 61739.34,
 61759.37,
 61766.87,
 61772.18,
 61778.82,
 61784.49,
 61795.51,
 61803.42,
 61812.64,
 61821.68,
 61826.54,
 61832.05,
 61839.62,
 61841.38,
 61841.66,
 61841.64,
 61840.52,
 61840.27,
 61834.53,
 61833.4,
 61830.96,
 61831.0,
 61825.65,
 61818.89,
 61816.74,
 61815.54,
 61815.0,
 61814.27,
 61813.72,
 61813.2,
 61811.5,
 61810.75,
 61810.68,
 61811.07,
 61811.39,
 61812.09,
 61812.56,
 61814.77,
 61816.65,
 61825.63,
 61839.76,
 61845.53,
 61916.57,
 61997.2,
 62044.85,
 62111.21,
 62147.65,
 62177.22,
 62238.51,
 62309.06,
 62340.05,
 62358.61,
 62385.52,
 62415.87,
 62456.62,
 62477.8,
 62497.17,
 62512.12,
 62525.21,
 62535.55,
 62554.86,
 62581.28,
 62603.01,
 62623.41,
 62638.4,
 62657.74,
 62705.54,
 62737.37,
 62777.55,
 62806.47,
 62850.41,
 62878.18,
 62896.31,
 62908.86,
 62915.63,
 62922.91,
 62930.0,
 62938.13,
 62945.47,
 62951.63,
 62956.04,
 62976.2,
 62983.22,
 62989.33,
 63006.57,
 63049.46,
 63067.17,
 63078.09,
 63092.24,
 63104.33,
 63122.25,
 63140.7,
 63165.81,
 63233.57,
 63257.5,
 63275.77,
 63297.46,
 63314.63,
 63322.43,
 63327.72,
 63332.82,
 63343.68,
 63360.94,
 63366.96,
 63375.13,
 63382.58,
 63389.26,
 63393.36,
 63401.06,
 63414.61,
 63421.73,
 63431.21,
 63453.39,
 63471.84,
 63481.52,
 63492.07,
 63512.36,
 63522.12,
 63528.59,
 63535.62,
 63538.8,
 63541.94,
 63546.02,
 63549.48,
 63556.6,
 63561.45,
 63564.72,
 63567.36,
 63581.55,
 63590.24,
 63595.07,
 63598.71,
 63603.84,
 63616.07,
 63622.73,
 63629.16,
 63657.52,
 63677.39,
 63693.15,
 63706.09,
 63715.94,
 63724.06,
 63736.58,
 63744.03,
 63748.58,
 63771.96,
 63778.02,
 63782.36,
 63787.45,
 63791.17,
 63797.39,
 63807.44,
 63815.03,
 63820.34,
 63834.83,
 63847.79,
 63860.57,
 63871.98,
 63880.64,
 63887.89,
 63906.89,
 63917.78,
 63928.24,
 63943.53,
 63958.84,
 63984.68,
 64043.49,
 64083.04,
 64110.56,
 64257.72,
 64367.18,
 64421.8,
 64462.29,
 64583.02,
 64679.93,
 64755.69,
 64815.8,
 64855.04,
 64881.51,
 64915.11,
 64946.72,
 64980.21,
 65006.44,
 65031.54,
 65064.52,
 65112.73,
 65157.2,
 65212.88,
 65253.27,
 65290.84,
 65326.21,
 65356.23,
 65367.42,
 65387.16,
 65399.59,
 65407.24,
 65423.87,
 65434.24,
 65447.67,
 65458.21,
 65472.76,
 65481.95,
 65497.42,
 65506.05,
 65514.05,
 65523.22,
 65537.25,
 65543.99,
 65552.89,
 65563.55,
 65579.41,
 65593.8,
 65616.53,
 65634.43,
 65647.68,
 65666.81,
 65692.47,
 65703.38,
 65718.34,
 65732.75,
 65741.45,
 65747.78,
 65755.97,
 65761.71,
 65765.95,
 65771.75,
 65778.14,
 65783.25,
 65789.08,
 65797.37,
 65803.64,
 65811.41,
 65818.32,
 65834.62,
 65856.59,
 65889.9,
 65906.19,
 65916.16,
 65921.15,
 65926.21,
 65936.85,
 65941.92,
 65958.26,
 65980.59,
 65984.47,
 65988.64,
 65993.57,
 65995.99,
 65999.78,
 66003.88,
 66007.83,
 66012.26,
 66017.58,
 66021.07,
 66024.08,
 66026.55,
 66028.38,
 66030.52,
 66032.95,
 66038.83,
 66046.73,
 66056.56,
 66064.71,
 66075.87,
 66087.14,
 66092.75,
 66097.18,
 66099.65,
 66101.54,
 66103.89,
 66105.81,
 66107.83,
 66110.04,
 66113.19,
 66115.86,
 66117.36,
 66119.44,
 66121.31,
 66125.07,
 66128.49,
 66133.78,
 66141.57,
 66147.42,
 66154.45,
 66158.38,
 66162.7,
 66165.64,
 66167.71,
 66170.12,
 66171.8,
 66173.25,
 66174.72,
 66176.22,
 66179.36,
 66181.42,
 66183.0,
 66186.41,
 66189.25,
 66190.87,
 66192.22,
 66193.92,
 66198.02,
 66203.51,
 66206.84,
 66210.02,
 66213.39,
 66216.35,
 66218.63,
 66222.96,
 66229.51,
 66234.06,
 66236.32,
 66238.27,
 66239.59,
 66240.54,
 66244.59,
 66246.39,
 66248.64,
 66251.17,
 66255.48,
 66260.03,
 66266.12,
 66268.61,
 66272.59,
 66275.32,
 66278.52,
 66282.64,
 66285.64,
 66288.45,
 66292.29,
 66295.33,
 66301.13,
 66310.73,
 66339.39,
 66355.14,
 66361.83,
 66367.02,
 66376.26,
 66381.69,
 66384.62,
 66388.1,
 66391.98,
 66396.99,
 66404.95,
 66412.81,
 66421.85,
 66426.24,
 66429.35,
 66432.06,
 66435.59,
 66440.21,
 66444.98,
 66452.96,
 66456.66,
 66460.23,
 66467.75,
 66474.02,
 66478.73,
 66482.57,
 66485.55,
 66489.21,
 66494.97,
 66496.93,
 66498.5,
 66500.91,
 66502.28,
 66504.16,
 66506.72,
 66510.29,
 66513.99,
 66517.41,
 66519.57,
 66521.73,
 66526.31,
 66529.89,
 66532.58,
 66534.28,
 66535.95,
 66539.09,
 66544.93,
 66548.09,
 66551.4,
 66554.04,
 66555.47,
 66556.6,
 66557.58,
 66558.41,
 66559.49,
 66560.3,
 66561.19,
 66562.29,
 66563.55,
 66565.97,
 66567.47,
 66569.89,
 66571.23,
 66575.02,
 66578.06,
 66581.31,
 66582.98,
 66585.08,
 66586.96,
 66591.18,
 66597.19,
 66603.85,
 66608.76,
 66612.14,
 66625.48,
 66631.79,
 66637.91,
 66642.29,
 66643.52,
 66644.65,
 66645.89,
 66647.22,
 66649.14,
 66651.56,
 66652.6,
 66654.59,
 66656.49,
 66658.02,
 66660.57,
 66662.02,
 66664.12,
 66666.35,
 66669.05,
 66677.41,
 66683.25,
 66688.72,
 66690.46,
 66692.28,
 66693.2,
 66694.22,
 66696.86,
 66697.72,
 66698.53,
 66699.06,
 66700.12,
 66700.97,
 66701.77,
 66702.29,
 66702.8,
 66703.31,
 66703.82,
 66704.25,
 66704.78,
 66705.38,
 66705.95,
 66706.44,
 66706.83,
 66707.51,
 66708.23,
 66708.88,
 66709.41,
 66709.89,
 66711.86,
 66712.34,
 66712.62,
 66713.2,
 66713.69,
 66714.14,
 66714.42,
 66714.96,
 66715.67,
 66716.22,
 66716.63,
 66716.95,
 66717.3,
 66717.87,
 66718.44,
 66719.03,
 66720.39,
 66720.86,
 66723.38,
 66725.34,
 66726.87,
 66731.95,
 66733.0,
 66733.95,
 66736.18,
 66738.38,
 66740.49,
 66741.07,
 66741.52,
 66742.13,
 66742.61,
 66743.49,
 66746.81,
 66750.07,
 66751.89,
 66754.05,
 66756.41,
 66764.94,
 66769.77,
 66774.35,
 66776.69,
 66780.11,
 66783.24,
 66791.19,
 66804.12,
 66817.23,
 66824.34,
 66830.19,
 66832.94,
 66835.37,
 66837.72,
 66841.06,
 66842.93,
 66844.77,
 66846.2,
 66848.93,
 66850.61,
 66852.09,
 66853.47,
 66854.78,
 66856.23,
 66859.73,
 66861.52,
 66863.76,
 66867.22,
 66869.14,
 66870.74,
 66873.8,
 66882.54,
 66896.54,
 66912.16,
 66932.01,
 66939.84,
 66954.71,
 66962.25,
 66965.58,
 66968.45,
 66972.4,
 66974.86,
 66980.4,
 66989.12,
 66996.89,
 67001.27,
 67009.17,
 67013.76,
 67020.8,
 67028.5,
 67034.68,
 67038.84,
 67043.43,
 67047.48,
 67055.17,
 67064.1,
 67073.74,
 67090.3,
 67099.52,
 67107.92,
 67118.13,
 67123.4,
 67127.38,
 67129.39,
 67131.52,
 67137.09,
 67139.63,
 67142.3,
 67144.81,
 67147.1,
 67150.25,
 67153.72,
 67156.7,
 67159.86,
 67162.54,
 67165.53,
 67167.75,
 67172.05,
 67179.72,
 67190.27,
 67199.21,
 67207.92,
 67219.37,
 67226.08,
 67229.11,
 67235.67,
 67242.95,
 67244.88,
 67248.03,
 67250.93,
 67252.87,
 67255.21,
 67257.43,
 67259.66,
 67265.08,
 67274.16,
 67277.28,
 67281.69,
 67285.53,
 67288.7,
 67291.8,
 67298.8,
 67328.45,
 67336.78,
 67342.03,
 67350.19,
 67355.48,
 67364.9,
 67383.93,
 67388.35,
 67390.98,
 67392.18,
 67393.7,
 67394.82,
 67396.29,
 67397.65,
 67398.43,
 67399.44,
 67400.5,
 67401.36,
 67402.35,
 67403.79,
 67404.75,
 67405.6,
 67406.6,
 67407.98,
 67409.06,
 67411.02,
 67412.39,
 67413.27,
 67414.69,
 67415.93,
 67416.62,
 67417.27,
 67418.02,
 67418.47,
 67418.96,
 67419.57,
 67420.22,
 67420.71,
 67421.58,
 67422.29,
 67422.79,
 67423.27,
 67423.87,
 67424.75,
 67425.26,
 67425.74,
 67426.31,
 67426.86,
 67429.23,
 67433.16,
 67434.87,
 67436.73,
 67437.77,
 67438.54,
 67440.71,
 67442.32,
 67443.19,
 67443.98,
 67444.77,
 67445.24,
 67446.42,
 67447.7,
 67449.73,
 67450.65,
 67451.43,
 67452.33,
 67454.32,
 67455.93,
 67457.24,
 67459.04,
 67460.11,
 67461.27,
 67462.36,
 67464.34,
 67466.44,
 67472.85,
 67476.35,
 67478.15,
 67481.74,
 67485.2,
 67488.38,
 67489.24,
 67490.15,
 67491.0,
 67492.06,
 67495.7,
 67500.16,
 67501.52,
 67503.53,
 67504.21,
 67504.55,
 67504.78,
 67504.74,
 67504.04,
 67502.84,
 67501.63,
 67500.69,
 67498.84,
 67497.86,
 67493.22,
 67490.81,
 67489.19,
 67488.27,
 67488.05,
 67487.89,
 67487.81,
 67487.77,
 67487.71,
 67487.57,
 67487.17,
 67487.07,
 67487.01,
 67487.01,
 67486.89,
 67486.78,
 67486.71,
 67486.68,
 67486.84,
 67487.44,
 67487.74,
 67496.15,
 67501.93,
 67508.14,
 67512.87,
 67515.94,
 67518.91,
 67526.92,
 67529.46,
 67530.35,
 67531.32,
 67531.88,
 67532.22,
 67532.74,
 67533.13,
 67533.66,
 67533.38,
 67533.3,
 67533.3,
 67533.26,
 67533.32,
 67533.37,
 67533.2,
 67533.37,
 67533.64,
 67534.65,
 67535.19,
 67534.9,
 67532.18,
 67530.2,
 67529.4,
 67528.8,
 67528.06,
 67527.51,
 67527.14,
 67526.86,
 67526.56,
 67525.92,
 67525.33,
 67524.83,
 67524.41,
 67524.11,
 67523.6,
 67523.18,
 67522.61,
 67522.06,
 67521.59,
 67521.19,
 67520.74,
 67520.33,
 67519.81,
 67518.5,
 67516.93,
 67506.15,
 67502.61,
 67498.93,
 67497.04,
 67495.38,
 67492.84,
 67491.53,
 67490.99,
 67489.82,
 67489.28,
 67488.85,
 67488.23,
 67487.58,
 67487.0,
 67485.9,
 67484.36,
 67483.97,
 67483.52,
 67483.06,
 67482.44,
 67482.03,
 67481.61,
 67480.88,
 67479.86,
 67479.33,
 67478.78,
 67478.32,
 67477.97,
 67476.9,
 67476.55,
 67476.07,
 67475.79,
 67475.5,
 67475.15,
 67474.94,
 67474.72,
 67474.44,
 67474.06,
 67473.55,
 67473.22,
 67472.96,
 67471.93,
 67471.19,
 67470.76,
 67470.47,
 67470.02,
 67469.44,
 67469.17,
 67468.86,
 67468.53,
 67468.32,
 67468.15,
 67467.86,
 67467.67,
 67466.84,
 67466.54,
 67465.95,
 67464.94,
 67463.71,
 67463.06,
 67462.5,
 67461.98,
 67460.91,
 67459.54,
 67458.58,
 67456.55,
 67454.21,
 67453.08,
 67451.5,
 67447.87,
 67445.1,
 67442.4,
 67438.77,
 67436.69,
 67435.24,
 67434.55,
 67433.13,
 67432.58,
 67432.22,
 67431.3,
 67428.54,
 67418.19,
 67411.17,
 67408.92,
 67406.92,
 67405.12,
 67402.79,
 67401.22,
 67400.33,
 67399.0,
 67397.29,
 67394.1,
 67390.0,
 67382.63,
 67373.16,
 67366.22,
 67360.8,
 67356.89,
 67353.62,
 67347.42,
 67341.89,
 67339.58,
 67337.99,
 67336.31,
 67334.07,
 67329.5,
 67327.57,
 67325.63,
 67323.6,
 67322.49,
 67321.28,
 67319.26,
 67317.88,
 67316.29,
 67314.99,
 67311.79,
 67310.52,
 67309.32,
 67306.63,
 67304.85,
 67303.07,
 67301.25,
 67300.26,
 67299.24,
 67297.87,
 67297.1,
 67296.42,
 67295.79,
 67293.55,
 67292.15,
 67290.88,
 67290.13,
 67289.21,
 67287.85,
 67286.48,
 67284.88,
 67283.88,
 67282.79,
 67281.79,
 67280.43,
 67278.96,
 67274.41,
 67270.13,
 67267.04,
 ...]

In [15]:
#data is df  : df
#period      : range atr
Get_atr(data=df, period=14)

0        352.010000
1        328.970000
2        309.823333
3        266.920000
4        256.528000
           ...
5025    1389.550714
5026    1303.016429
5027    1228.133571
5028    1213.065000
5029    1193.727857
Length: 5030, dtype: float64

In [16]:
#high is price  : high list
#low is price   : low list
#close is price : close list
#period         : range cci
Get_cci(close=df["close"],high=df["high"],low=df["low"], period=20)

array([        nan,         nan,         nan, ..., 71.17858288,
       74.31772449, 71.56995349])

In [17]:
#high is price  : high list
#low is price   : low list
#close is price : close list
#get di false is get only adx true is get adx,Di,Di- 3parameater
aadx,DiPlus,DiMinus = Get_AdxandDi(High=df["high"],Low=df["low"],Close=df["close"],GetDi = True)
adx = Get_AdxandDi(High=df["high"],Low=df["low"],Close=df["close"],GetDi = False)

In [18]:
#df is dataframe
#atr_period is range atr 
#mmultiplier is range supertrend
Get_Supertrend(df=df, atr_period=14, multiplier=3)

,Unnamed: 0,open,high,low,close,volume,datetime,Supertrend,Final Lowerband,Final Upperband
0,0,63074.00,63094.01,62742.00,62840.73,768.12,2024-05-10 00:00:00,True,NaN,NaN
1,1,62840.72,62968.00,62662.07,62883.50,776.17,2024-05-10 01:00:00,True,NaN,NaN
2,2,62883.50,63043.29,62771.76,62910.61,605.45,2024-05-10 02:00:00,True,NaN,NaN
3,3,62910.62,62932.15,62793.94,62916.16,586.05,2024-05-10 03:00:00,True,NaN,NaN
4,4,62916.16,63008.00,62793.04,62929.99,607.57,2024-05-10 04:00:00,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5025,5025,102764.01,103159.76,102565.63,102698.24,2204.40,2024-12-05 09:00:00,True,99559.229701,NaN
5026,5026,102698.25,102920.00,102260.00,102280.62,1591.37,2024-12-05 10:00:00,True,99559.229701,NaN
5027,5027,102280.62,102672.84,102237.79,102566.91,1395.71,2024-12-05 11:00:00,True,99559.229701,NaN
5028,5028,102566.91,103295.99,102452.95,102846.15,2215.64,2024-12-05 12:00:00,True,99791.353054,NaN
5029,5029,102846.16,103250.00,102684.73,103006.42,1259.18,2024-12-05 13:00:00,True,99983.341407,NaN

In [22]:
clean_data_frame(df)



# ClearFloatDF(df,2)

KeyError: "['unnamed: 0'] not found in axis"